/**
 * Curated database of 10 Creative Commons licensed artists across multiple genres.
 * All artists are CC BY, CC BY-SA, or CC0 — safe for commercial use.
 *
 * Audio files are self-hosted on media.musicmindacademy.com (Cloudflare R2).
 * When adding audio, set each track's audioUrl to the R2 path.
 *
 * Attribution format per license:
 *   CC BY:    "Music by [Artist] — licensed under CC BY 4.0"
 *   CC BY-SA: "Music by [Artist] — licensed under CC BY-SA 4.0"
 *   CC0:      No attribution required (but nice to credit anyway)
 */

const ARTISTS = [
  // ── LO-FI HIP-HOP ──────────────────────────────────
  {
    id: 'holiznacc0',
    name: 'HoliznaCC0',
    genre: 'Hip-Hop',
    subgenre: 'Lo-fi Hip-Hop / Chiptune',
    location: 'Pittsburgh, Pennsylvania',
    license: 'CC0',
    fmaUrl: 'https://freemusicarchive.org/music/holiznacc0/',
    albumTitle: 'Lo-fi And Chill',
    imageUrl: 'https://freemusicarchive.org/image/?file=artist_image%2FlM2G8yAdu4LWzK5a3ZHKeJQnMkMe1u9qQzZvJ5HY.png&width=290&height=290&type=artist',
    bio: 'HoliznaCC0 is a producer from Pittsburgh who makes lo-fi hip-hop, chiptune, rock, and gaming soundtracks — and gives it ALL away for free. They started recording as a teenager and have built up a massive catalog of over 570 tracks, all released under CC0, which means anyone can use the music for anything.',
    whyInteresting: 'They prove you don\'t need a record deal to have a massive impact — their music has been used in thousands of videos, games, and projects worldwide because they chose to give it away completely free.',
    tags: ['lo-fi', 'chiptune', 'gaming', 'beats', 'pittsburgh', 'cc0'],
    formed: '2015',
    members: 'Solo',
    totalAlbums: 30,
    instruments: ['Synthesizers', 'Drum Machines', 'Guitar', 'Bass'],
    moods: ['Chill', 'Retro', 'Groovy'],
    influences: ['Nujabes', 'Boards of Canada', 'Video Game Soundtracks'],
    similarArtists: ['kellee-maize', 'ketsa'],
    funFacts: [
      'All 570+ tracks are CC0 — the most generous license possible, meaning anyone can use them for anything',
      'Some tracks were recorded when they were still a teenager',
      'Over 5.5 million plays on Free Music Archive alone',
    ],
    tracks: [
      { title: 'Foggy Headed', duration: '4:06', audioUrl: '/audio/artists/holiznacc0/foggy-headed.mp3' },
      { title: 'Whatever', duration: '3:56', audioUrl: '/audio/artists/holiznacc0/whatever.mp3' },
      { title: 'Plants.mp3', duration: '3:52', audioUrl: '/audio/artists/holiznacc0/plants.mp3' },
      { title: 'Clouds', duration: '3:49', audioUrl: '/audio/artists/holiznacc0/clouds.mp3' },
    ],
  },

  // ── 1000 Handz — REMOVED: not truly hip-hop, no artist photo, weak profile ──
  // Audio files still in public/audio/artists/1000-handz/ if needed later

  // ── JAZZ / SOUL / LATIN ─────────────────────────────
  {
    id: 'ketsa',
    name: 'Ketsa',
    genre: 'Jazz',
    subgenre: 'Jazz / Soul / Latin / Trip-Hop',
    location: 'London, England',
    license: 'CC BY',
    fmaUrl: 'https://freemusicarchive.org/music/Ketsa/',
    albumTitle: 'CC BY: FREE TO USE FOR ANYTHING',
    imageUrl: 'https://freemusicarchive.org/image/?file=artist_image%2FCIPeL9rmMA9ojtVqaoleGmXXoM7V2cvVwmf7SaUn.jpg&width=290&height=290&type=artist',
    bio: 'Ketsa is London-based producer Dominic Giam, a veteran musician who has been making music since 1997. He started as a techno DJ before switching to his Ketsa project, and has since released over 1,400 tracks spanning jazz, soul, hip-hop, Latin, and ambient — streamed over 16 million times online.',
    whyInteresting: 'Ketsa has been making music for almost 30 years and has one of the largest Creative Commons catalogs in the world, with tracks reaching everything from yoga studios to Volvo commercials.',
    tags: ['jazz', 'soul', 'latin', 'trip-hop', 'london', 'veteran'],
    formed: '1997',
    members: 'Solo',
    totalAlbums: 40,
    instruments: ['Synthesizers', 'Keyboards', 'Guitar', 'Bass', 'DJ Turntables'],
    moods: ['Mellow', 'Soulful', 'Dreamy'],
    influences: ['DJ Shadow', 'Massive Attack', 'Bonobo'],
    similarArtists: ['broke-for-free', 'jahzzar'],
    funFacts: [
      'His music has been used by National Geographic, the United Nations, Audi, and Volvo',
      'Over 1,400 tracks spanning jazz, soul, hip-hop, Latin, and ambient',
      'Co-founded the Independent Music Licensing Collective (IMLC)',
    ],
    tracks: [
      { title: 'Trench Work', duration: '3:30', audioUrl: '/audio/artists/ketsa/trench-work.mp3' },
      { title: 'Doobie', duration: '3:20', audioUrl: '/audio/artists/ketsa/doobie.mp3' },
      { title: 'Will Make You Happy', duration: '3:35', audioUrl: '/audio/artists/ketsa/will-make-you-happy.mp3' },
      { title: 'No Limits', duration: '3:36', audioUrl: '/audio/artists/ketsa/no-limits.mp3' },
      { title: 'All Ways', duration: '3:15', audioUrl: '/audio/artists/ketsa/all-ways.mp3' },
    ],
  },

  // ── ELECTRONIC / INDIE ──────────────────────────────
  {
    id: 'broke-for-free',
    name: 'Broke For Free',
    genre: 'Electronic',
    subgenre: 'Electropop / Indie Electronic',
    location: 'Oakland, California',
    license: 'CC BY',
    fmaUrl: 'https://freemusicarchive.org/music/Broke_For_Free/',
    albumTitle: 'Directionless EP',
    imageUrl: 'https://freemusicarchive.org/image/?file=artist_image%2FE0XCVaXi3oUHZIJJ90mqijoKKgMw3abve7Fd7Apv.jpg&width=290&height=290&type=artist',
    bio: 'Broke For Free is the music project of Tom Cascino from Oakland, California, who blends glitchy hip-hop beats, dreamy synths, and euphoric guitar melodies into music that sounds like a beautiful daydream. He gives it all away because he believes music should be shared.',
    whyInteresting: 'He turned down a deal with Universal Music Group to stay independent and keep giving his music away for free — and ended up scoring one of YouTube\'s biggest cooking shows, Binging with Babish.',
    tags: ['electronic', 'indie', 'feel-good', 'glitch', 'oakland'],
    formed: '2010',
    members: 'Solo',
    totalAlbums: 14,
    instruments: ['Ableton Live', 'Synthesizers', 'Guitar', 'Samplers'],
    moods: ['Dreamy', 'Uplifting', 'Warm'],
    influences: ['RAC', 'Slow Magic', 'Odesza'],
    similarArtists: ['jahzzar', 'ketsa'],
    funFacts: [
      'Turned down a deal with Universal Music Group to stay independent and keep his music free',
      'Scores the YouTube cooking show Binging with Babish (10+ million subscribers)',
      '"Night Owl" is the #1 most-played track in Free Music Archive history',
    ],
    tracks: [
      { title: 'Nothing Like Captain Crunch', duration: '5:12', audioUrl: '/audio/artists/broke-for-free/nothing-like-captain-crunch.mp3' },
      { title: 'Calm Down', duration: '4:45', audioUrl: '/audio/artists/broke-for-free/calm-down.mp3' },
      { title: 'The Great', duration: '5:57', audioUrl: '/audio/artists/broke-for-free/the-great.mp3' },
      { title: 'Caught In The Beat', duration: '4:23', audioUrl: '/audio/artists/broke-for-free/caught-in-the-beat.mp3' },
    ],
  },

  // ── FOLK ROCK ───────────────────────────────────────
  {
    id: 'josh-woodward',
    name: 'Josh Woodward',
    genre: 'Folk / Country',
    subgenre: 'Folk Rock / Acoustic / Americana',
    location: 'Ann Arbor, Michigan',
    license: 'CC BY',
    fmaUrl: 'https://freemusicarchive.org/music/Josh_Woodward/',
    albumTitle: 'Dirty Wings',
    imageUrl: 'https://freemusicarchive.org/image/?file=images%2Fartists%2FJosh_Woodward_-_2013101594658340.jpg&width=290&height=290&type=artist',
    bio: 'Josh Woodward is a singer-songwriter from Ann Arbor, Michigan who plays guitar, bass, drums, and keyboards — and records everything himself. Since 2004 he has released 14 studio albums and over 250 songs, and every single one is free to download because he believes great music should be available to everyone.',
    whyInteresting: 'Josh is a true one-person band who writes, plays every instrument, records, and produces all his own music — and has been giving it all away for free for over 20 years.',
    tags: ['folk', 'acoustic', 'singer-songwriter', 'michigan', 'one-man-band'],
    formed: '2004',
    members: 'Solo',
    totalAlbums: 14,
    instruments: ['Acoustic Guitar', 'Electric Guitar', 'Bass', 'Drums', 'Keyboards'],
    moods: ['Warm', 'Reflective', 'Catchy'],
    influences: ['Elliott Smith', 'Wilco', 'Greg Brown'],
    similarArtists: ['cullah', 'broke-for-free'],
    funFacts: [
      'Won the Jamendo Best Pop Artist award in 2011, beating out thousands of other artists',
      'Grew up in tiny Van Buren, Ohio and taught himself to play multiple instruments',
      '"Goodbye to Spring" has over 500,000 streams on Spotify — proof that free music still gets heard',
    ],
    tracks: [
      { title: 'I Want To Destroy Something Beautiful', duration: '3:48', audioUrl: '/audio/artists/josh-woodward/i-want-to-destroy-something-beautiful.mp3' },
      { title: 'Gravity', duration: '3:55', audioUrl: '/audio/artists/josh-woodward/gravity.mp3' },
      { title: 'Stickybee', duration: '3:45', audioUrl: '/audio/artists/josh-woodward/stickybee.mp3' },
      { title: 'Insomnia', duration: '3:30', audioUrl: '/audio/artists/josh-woodward/insomnia.mp3' },
    ],
  },

  // ── ROCK / FUNK / RAP ──────────────────────────────
  {
    id: 'cullah',
    name: 'Cullah',
    genre: 'Rock',
    subgenre: 'Rock / Funk / Rap / Folk',
    location: 'Milwaukee, Wisconsin',
    license: 'CC BY',
    fmaUrl: 'https://freemusicarchive.org/music/MC_Cullah/',
    albumTitle: 'Cullahtivation',
    imageUrl: 'https://freemusicarchive.org/image/?file=images%2Fartists%2FCullah_-_20180503171218146.jpg&width=290&height=290&type=artist',
    bio: 'Cullah is a one-man music machine from Milwaukee who has released a brand-new album every single year on his birthday since he was 15 years old. He mixes so many styles — folk, electronic, hip-hop, rock — that people call him "The Beck of Milwaukee." His music has been used in over 10,000 projects including the movie Expendables 4.',
    whyInteresting: 'He\'s proven you can build a full music career by giving your music away for free under Creative Commons while still getting placed in major movies and video games.',
    tags: ['eclectic', 'multi-genre', 'milwaukee', 'one-man-band', 'folk', 'funk', 'rap'],
    formed: '2006',
    members: 'Solo',
    totalAlbums: 20,
    instruments: ['Vocals', 'Guitar', 'Banjo', 'Samplers', 'Synths'],
    moods: ['Eclectic', 'Adventurous', 'Soulful'],
    influences: ['Beck', 'Folk/Bluegrass Tradition', 'Electronic Producers'],
    similarArtists: ['josh-woodward', 'komiku'],
    funFacts: [
      'Has released an album every year on his birthday (April 27th) since 2006 — that\'s 20 albums!',
      'Won a Wisconsin Area Music Industry Award for "Unique Album of the Year" in 2023',
      'Draws creative inspiration from Tolkien\'s Lord of the Rings and mythology',
    ],
    tracks: [
      { title: 'Cullahtivation Revelation', duration: '3:50', audioUrl: '/audio/artists/cullah/cullahtivation-revelation.mp3' },
      { title: 'Falling', duration: '3:10', audioUrl: '/audio/artists/cullah/falling.mp3' },
      { title: 'Runaway', duration: '4:18', audioUrl: '/audio/artists/cullah/runaway.mp3' },
      { title: 'A Trying Shame', duration: '3:26', audioUrl: '/audio/artists/cullah/a-trying-shame.mp3' },
    ],
  },

  // ── POP / R&B / FUNK ───────────────────────────────
  {
    id: 'pamela-yuen',
    name: 'Pamela Yuen',
    genre: 'Pop',
    subgenre: 'Pop / R&B / Funk / Cinematic',
    location: 'Kuala Lumpur, Malaysia',
    license: 'CC BY',
    fmaUrl: 'https://freemusicarchive.org/music/pamela-yuen/',
    albumTitle: 'Multigenre Pop Vibes',
    imageUrl: 'https://freemusicarchive.org/image/?file=artist_image%2FJJ7dDFZg9HlABRKZIVlNrUcwSdYEDHeKxkOr0fa1.jpg&width=290&height=290&type=artist',
    bio: 'Pamela Yuen is a Malaysian-Chinese composer from Kuala Lumpur whose motto is "Music for imaginative minds and weary souls." She writes everything from funky pop jams to cinematic orchestral pieces and beautiful piano compositions, and gives it all away under Creative Commons.',
    whyInteresting: 'She bridges Eastern and Western musical traditions from Malaysia, creating everything from pop to orchestral scores and giving it all away to help storytellers worldwide.',
    tags: ['pop', 'funk', 'rnb', 'cinematic', 'malaysia', 'female-composer'],
    formed: '2018',
    members: 'Solo',
    totalAlbums: 7,
    instruments: ['Piano', 'Keyboards', 'Digital Orchestration'],
    moods: ['Dreamy', 'Cinematic', 'Uplifting'],
    influences: ['Film Score Composers', 'Neo-Classical Piano', 'Pop/R&B'],
    similarArtists: ['ketsa', 'kevin-macleod'],
    funFacts: [
      'Composes across a huge range — one album might be quirky pop and the next dramatic film music',
      'Over 80,000 plays on Free Music Archive with 50+ tracks available',
      'Believes music has "transformative and restorative power" and wants creators to access it for free',
    ],
    tracks: [
      { title: 'Follow', duration: '3:30', audioUrl: '/audio/artists/pamela-yuen/follow.mp3' },
      { title: 'Quiet Years', duration: '4:15', audioUrl: '/audio/artists/pamela-yuen/quiet-years.mp3' },
      { title: 'The Unfolding', duration: '4:00', audioUrl: '/audio/artists/pamela-yuen/the-unfolding.mp3' },
      { title: 'Our Feet Will Have Wings', duration: '3:45', audioUrl: '/audio/artists/pamela-yuen/our-feet-will-have-wings.mp3' },
    ],
  },

  // ── CHIPTUNE / ADVENTURE ────────────────────────────
  {
    id: 'komiku',
    name: 'Komiku',
    genre: 'Electronic',
    subgenre: 'Chiptune / Adventure Soundtrack / Punk',
    location: 'Marseille, France',
    license: 'CC0',
    fmaUrl: 'https://freemusicarchive.org/music/Komiku/',
    albumTitle: "It's Time for Adventure!",
    imageUrl: 'https://freemusicarchive.org/image/?file=images%2Fartists%2FKomiku_-_20160721122625292.jpg&width=290&height=290&type=artist',
    bio: 'Komiku is a wildly creative musician from Marseille, France who makes music that sounds like it belongs in the coolest video game you\'ve never played. Under this name, Rrrrrose Azerty creates chiptune adventure soundtracks inspired by games like Undertale and shows like Steven Universe — with over 600 tracks all completely free under CC0.',
    whyInteresting: 'They create entire imaginary video game soundtracks for games that don\'t even exist yet, blending chiptune, punk, folk, and classical guitar into wild adventure music.',
    tags: ['chiptune', '8-bit', 'adventure', 'punk', 'gaming', 'french', 'cc0'],
    formed: '2010',
    members: 'Solo',
    totalAlbums: 25,
    instruments: ['Electric Guitar', 'Classical Guitar', 'Synthesizers', 'Chiptune Tools'],
    moods: ['Adventurous', 'Playful', 'Energetic'],
    influences: ['Toby Fox (Undertale)', 'Rebecca Sugar (Steven Universe)', 'Punk'],
    similarArtists: ['cullah', 'holiznacc0'],
    funFacts: [
      'Once recorded an entire 70-track album in just TEN DAYS — that\'s seven songs a day!',
      'Also releases music as "Loyalty Freak Music" — over 600 tracks total across both projects',
      'Also develops video games and participates in FAWM (writing 14 songs in 28 days)',
    ],
    tracks: [
      { title: 'Tale on the Late (Main Theme)', duration: '2:42', audioUrl: '/audio/artists/komiku/tale-on-the-late.mp3' },
      { title: 'Remember the Time We Used to Play', duration: '3:17', audioUrl: '/audio/artists/komiku/remember-the-time.mp3' },
      { title: 'The Road We Traveled', duration: '3:30', audioUrl: '/audio/artists/komiku/the-road-we-traveled.mp3' },
      { title: 'Friends', duration: '2:00', audioUrl: '/audio/artists/komiku/friends.mp3' },
    ],
  },

  // ── INDIE / CINEMATIC ───────────────────────────────
  {
    id: 'jahzzar',
    name: 'Jahzzar',
    genre: 'Indie / Alternative',
    subgenre: 'Indie Rock / Cinematic / Shoegaze',
    location: 'Gijon, Spain',
    license: 'CC BY-SA',
    fmaUrl: 'https://freemusicarchive.org/music/Jahzzar/',
    albumTitle: 'HiFi City Tales',
    imageUrl: 'https://freemusicarchive.org/image/?file=images%2Fartists%2FJahzzar_-_20160323124322227.jpg&width=290&height=290&type=artist',
    bio: 'Jahzzar is the musical project of Javier Suarez from Gijon, Spain — a composer who can make literally any style of music. One day he\'s recording dreamy indie rock, the next day it\'s funky dub, Celtic folk, or cinematic trip-hop. He composes, plays, and mixes everything himself.',
    whyInteresting: 'He\'s like a one-man film scoring studio from Spain who can jump between folk, electronic, shoegaze, and funk — making his library a treasure chest for any creative project.',
    tags: ['indie', 'cinematic', 'shoegaze', 'atmospheric', 'spain'],
    formed: '2012',
    members: 'Solo',
    totalAlbums: 16,
    instruments: ['Electric Guitar', 'Acoustic Guitar', 'Bass', 'Synths', 'Drum Machines'],
    moods: ['Cinematic', 'Dreamy', 'Groovy'],
    influences: ['Sonic Youth', 'Lotus Plaza', 'Stone Gossard (Pearl Jam)'],
    similarArtists: ['broke-for-free', 'kevin-macleod'],
    funFacts: [
      'Lists the Fender Jaguar guitar as one of his key influences — not a person, the actual guitar!',
      'His album Paris, Lisboa was inspired by walking the streets of Paris and Lisbon',
      'Over 8.2 million plays on Free Music Archive — one of the most popular CC artists ever',
    ],
    tracks: [
      { title: 'Curves', duration: '3:50', audioUrl: '/audio/artists/jahzzar/curves.mp3' },
      { title: 'MainSquare', duration: '3:10', audioUrl: '/audio/artists/jahzzar/mainsquare.mp3' },
      { title: 'Dew', duration: '3:30', audioUrl: '/audio/artists/jahzzar/dew.mp3' },
      { title: 'Bloom', duration: '3:37', audioUrl: '/audio/artists/jahzzar/bloom.mp3' },
    ],
  },

  // ── CINEMATIC / WORLD ───────────────────────────────
  {
    id: 'kevin-macleod',
    name: 'Kevin MacLeod',
    genre: 'World',
    subgenre: 'Cinematic / Classical / World',
    location: 'Green Bay, Wisconsin',
    license: 'CC BY',
    fmaUrl: 'https://freemusicarchive.org/music/Kevin_MacLeod/',
    albumTitle: 'Incompetech Collection',
    imageUrl: 'https://freemusicarchive.org/image/?file=images%2Fartists%2FKevin_MacLeod_-_20110715150335323.png&width=290&height=290&type=artist',
    bio: 'Kevin MacLeod might be the most-heard composer you\'ve never heard OF. From Green Bay, Wisconsin, he\'s composed over 2,000 pieces of music and given them ALL away for free — and his songs have been played BILLIONS of times on TikTok, YouTube, and even in Martin Scorsese\'s Oscar-nominated film Hugo.',
    whyInteresting: 'He\'s proof that giving music away for free can make you one of the most-heard composers in human history — his 2,000+ songs have been used in millions of YouTube videos, major films, and the game Kerbal Space Program.',
    tags: ['cinematic', 'classical', 'world', 'film-score', 'tiktok', 'famous'],
    formed: '1996',
    members: 'Solo',
    totalAlbums: 2000,
    instruments: ['Piano', 'Digital Orchestration', 'Full Virtual Orchestra'],
    moods: ['Epic', 'Cinematic', 'Whimsical'],
    influences: ['Classical Composers', 'Film Score Tradition', 'Ambient Music'],
    similarArtists: ['jahzzar', 'pamela-yuen'],
    funFacts: [
      '"Monkeys Spinning Monkeys" was played over 31.6 BILLION times on TikTok — more than 4x the world\'s population',
      'His music is literally in SPACE — featured on the International Space Station\'s live Earth camera feed',
      'A documentary about him called "Royalty Free: The Music of Kevin MacLeod" was released in 2020',
    ],
    tracks: [
      { title: 'Monkeys Spinning Monkeys', duration: '1:55', audioUrl: '/audio/artists/kevin-macleod/monkeys-spinning-monkeys.mp3' },
      { title: 'Casa Bossa Nova', duration: '2:52', audioUrl: '/audio/artists/kevin-macleod/casa-bossa-nova.mp3' },
      { title: 'Cold Funk', duration: '3:15', audioUrl: '/audio/artists/kevin-macleod/cold-funk.mp3' },
      { title: 'Sneaky Snitch', duration: '2:02', audioUrl: '/audio/artists/kevin-macleod/sneaky-snitch.mp3' },
    ],
  },

  // ── HIP-HOP / RAP (FEMALE) ─────────────────────────
  {
    id: 'kellee-maize',
    name: 'Kellee Maize',
    genre: 'Hip-Hop',
    subgenre: 'Conscious Hip-Hop / Positive Rap',
    location: 'Pittsburgh, Pennsylvania',
    license: 'CC BY',
    fmaUrl: 'https://freemusicarchive.org/music/Kellee_Maize/',
    albumTitle: 'The Remixes',
    imageUrl: 'https://freemusicarchive.org/image/?file=images%2Fartists%2FKellee_Maize_-_2016082183441482.png&width=290&height=290&type=artist',
    bio: 'Kellee Maize is a female rapper from Pittsburgh who makes hip-hop about empowerment, positivity, and standing up for what you believe in. She has performed at Bonnaroo, been featured in XXL Magazine, and topped Amazon\'s free albums chart — all while giving her music away for free under Creative Commons.',
    whyInteresting: 'She turned down the traditional music industry path and proved that a female rapper can build a massive following by giving her music away for free — over 13,000 YouTube videos use her tracks.',
    tags: ['hip-hop', 'female-rapper', 'conscious', 'empowerment', 'pittsburgh', 'positive'],
    formed: '2009',
    members: 'Solo',
    totalAlbums: 6,
    instruments: ['Vocals', 'Lyrics'],
    moods: ['Empowering', 'Energetic', 'Positive'],
    influences: ['Missy Elliott', 'Lauryn Hill', 'M.I.A.'],
    similarArtists: ['cullah', 'holiznacc0'],
    funFacts: [
      'Performed at Bonnaroo and was featured in XXL Magazine',
      'Over 13,000 YouTube videos use her Creative Commons music',
      'Topped Amazon\'s free albums chart and has been downloaded millions of times',
    ],
    tracks: [
      { title: 'In Tune (Remix 2)', duration: '3:00', audioUrl: '/audio/artists/kellee-maize/in-tune-remix-2.mp3' },
      { title: 'In Tune (J. Glaze Remix)', duration: '3:30', audioUrl: '/audio/artists/kellee-maize/in-tune-j-glaze-remix.mp3' },
      { title: 'I Insist', duration: '3:15', audioUrl: '/audio/artists/kellee-maize/i-insist.mp3' },
      { title: 'Mad Humans', duration: '2:30', audioUrl: '/audio/artists/kellee-maize/mad-humans.mp3' },
    ],
  },
  // ── R&B / POP (FEMALE) ───────────────────────────────
  {
    id: 'naishe',
    name: 'Naishe',
    genre: 'R&B / Soul',
    subgenre: 'R&B / Pop / Electronic',
    location: 'New York City, New York',
    license: 'CC0',
    fmaUrl: 'https://freemusicarchive.org/music/naishe/',
    albumTitle: 'Somewhere On Earth',
    imageUrl: 'https://freemusicarchive.org/image/?file=artist_image%2FNyO5xPozAmnoziwPp2Vi3AxiO854Aszy1u7LgUFl.jpg&width=290&height=290&type=artist',
    bio: 'Naishe is an R&B and pop singer-songwriter from New York City who won two Gold Medals at the NAACP ACT-SO Competition for Music Composition and Vocal Contemporary. Her soulful voice blends modern R&B with electronic pop production, creating music that feels both personal and powerful.',
    whyInteresting: 'A 2x NAACP Gold Medalist who releases all her music under CC0 — completely free for anyone to use — because she believes in making art accessible to everyone.',
    tags: ['rnb', 'pop', 'soul', 'female-singer', 'nyc', 'electronic', 'cc0'],
    formed: '2023',
    members: 'Solo',
    totalAlbums: 2,
    instruments: ['Vocals', 'Songwriting'],
    moods: ['Soulful', 'Modern', 'Smooth'],
    influences: ['SZA', 'H.E.R.', 'Jhene Aiko'],
    similarArtists: ['kellee-maize', 'pamela-yuen'],
    funFacts: [
      'Won two Gold Medals at the NAACP ACT-SO Competition — one of the most prestigious arts competitions for young Black artists',
      'Releases all her music under CC0 — completely free, no strings attached',
      'Her music blends R&B vocals with electronic and synth-pop production',
    ],
    tracks: [
      { title: 'Wonder', duration: '3:20', audioUrl: '/audio/artists/naishe/wonder.mp3' },
      { title: 'Body Lingo', duration: '3:00', audioUrl: '/audio/artists/naishe/body-lingo.mp3' },
      { title: 'Soul Searcher', duration: '3:15', audioUrl: '/audio/artists/naishe/soul-searcher.mp3' },
      { title: 'Classified', duration: '2:10', audioUrl: '/audio/artists/naishe/classified.mp3' },
    ],
  },
  // ── HIP-HOP / POP ───────────────────────────────────
  {
    id: 'superare',
    name: 'SUPERARE',
    genre: 'Hip-Hop',
    subgenre: 'Hip-Hop / Pop / Synth Pop',
    location: 'United States',
    license: 'CC0',
    fmaUrl: 'https://freemusicarchive.org/music/superare/',
    albumTitle: 'Pop Sensation',
    imageUrl: 'https://freemusicarchive.org/image/?file=artist_image%2Fnsj5DwBIPk6R4txIgtjoD5mKUKKd70QoDrtmjPhk.jpg&width=290&height=290&type=artist',
    bio: 'SUPERARE is a hip-hop and pop artist with one of the biggest catalogs on Free Music Archive — over 245 tracks and nearly half a million plays. Their music blends modern trap beats, catchy pop hooks, and smooth R&B vocals into tracks that sound like what you hear on TikTok and the radio.',
    whyInteresting: 'With over 660,000 combined plays and 339 tracks released under CC0, SUPERARE is proof that you can build a massive audience by giving your music away completely free.',
    tags: ['hip-hop', 'pop', 'trap', 'modern', 'cc0', 'vocals'],
    formed: '2020',
    members: 'Solo',
    totalAlbums: 15,
    instruments: ['Vocals', 'DAW', 'Synthesizers'],
    moods: ['Hype', 'Fun', 'Modern'],
    influences: ['Drake', 'The Weeknd', 'Post Malone'],
    similarArtists: ['kellee-maize', 'naishe'],
    funFacts: [
      'Over 660,000 plays across two artist names (SUPERARE and Tadz)',
      '339 tracks — all released under CC0, completely free to use',
      'Also releases music as "Tadz" with a more soulful, R&B-focused sound',
    ],
    tracks: [
      { title: 'Days of Our Lives (ft. Lee Swae)', duration: '3:30', audioUrl: '/audio/artists/superare/days-of-our-lives.mp3' },
      { title: '16', duration: '2:45', audioUrl: '/audio/artists/superare/16.mp3' },
      { title: 'Party Life', duration: '2:00', audioUrl: '/audio/artists/superare/party-life.mp3' },
      { title: 'SUPER Lit', duration: '3:10', audioUrl: '/audio/artists/superare/super-lit.mp3' },
    ],
  },
  // ── HIP-HOP / R&B ───────────────────────────────────
  {
    id: 'luce-lutu',
    name: 'Luce Lutu',
    genre: 'R&B / Soul',
    subgenre: 'Hip-Hop / Contemporary R&B',
    location: 'Seattle, Washington',
    license: 'CC BY',
    fmaUrl: 'https://freemusicarchive.org/music/Luce/',
    albumTitle: 'MUZM SZN',
    imageUrl: 'https://freemusicarchive.org/image/?file=images%2Fartists%2FLuce_-_20161006165842531.png&width=290&height=290&type=artist',
    bio: 'Luce Lutu is a hip-hop and R&B artist from Seattle who blends rich lyrics with soothing vocals and well-crafted beats. His music moves between smooth R&B singing and confident rap verses, creating a sound that feels both polished and personal.',
    whyInteresting: 'A Seattle-based artist and entrepreneur who fuses hip-hop swagger with soulful R&B vocals — proving the Pacific Northwest has more than just grunge and tech companies.',
    tags: ['hip-hop', 'rnb', 'soul', 'seattle', 'vocals', 'smooth'],
    formed: '2016',
    members: 'Solo',
    totalAlbums: 1,
    instruments: ['Vocals', 'Songwriting'],
    moods: ['Smooth', 'Confident', 'Soulful'],
    influences: ['Drake', 'Frank Ocean', 'The Weeknd'],
    similarArtists: ['naishe', 'superare'],
    funFacts: [
      'From Seattle — a city known for grunge rock, but Luce brings hip-hop and R&B to the Pacific Northwest',
      'Described as "fresh and unparalleled" — a true original in the CC music world',
      'Also an entrepreneur who balances music with business ventures',
    ],
    tracks: [
      { title: 'That Soul', duration: '3:00', audioUrl: '/audio/artists/luce-lutu/that-soul.mp3' },
      { title: 'The Juice', duration: '3:10', audioUrl: '/audio/artists/luce-lutu/the-juice.mp3' },
      { title: 'Seatown2LA', duration: '2:50', audioUrl: '/audio/artists/luce-lutu/seatown2la.mp3' },
      { title: '623am', duration: '3:00', audioUrl: '/audio/artists/luce-lutu/623am.mp3' },
    ],
  },
  // ── POP / SYNTH POP ──────────────────────────────────
  {
    id: 'soft-and-furious',
    name: 'Soft and Furious',
    genre: 'Pop',
    subgenre: 'Synth Pop / Electronic Pop / Dance',
    location: 'Unknown',
    license: 'CC0',
    fmaUrl: 'https://freemusicarchive.org/music/Soft_and_Furious/',
    albumTitle: 'You Know Where to Find Me',
    imageUrl: 'https://freemusicarchive.org/image/?file=images%2Fartists%2FSoft_and_Furious_-_20170401193146143.jpg&width=290&height=290&type=artist',
    bio: 'Soft and Furious creates catchy synth pop that blends electronic beats, R&B grooves, and danceable energy. With over 1.3 million plays on Free Music Archive, their music spans synth wave, chill out, techno, and big beat — all released under CC0 so anyone can use it.',
    whyInteresting: 'Over 1.3 million plays and everything is CC0 — one of the most popular artists on Free Music Archive who gives all their music away with zero restrictions.',
    tags: ['synth-pop', 'electronic', 'dance', 'pop', 'cc0'],
    formed: '2017',
    members: 'Solo',
    totalAlbums: 9,
    instruments: ['Synthesizers', 'Drum Machines', 'Samplers'],
    moods: ['Danceable', 'Dreamy', 'Energetic'],
    influences: ['Daft Punk', 'The Weeknd', 'Chromatics'],
    similarArtists: ['naishe', 'pamela-yuen'],
    funFacts: [
      'Over 1.3 million plays on Free Music Archive — one of the most popular CC0 artists ever',
      'Released 9 albums of synth pop, all completely free to use',
      'Music spans synth wave, R&B, techno, big beat, and chill out',
    ],
    tracks: [
      { title: 'Is This Fruit Edible?', duration: '1:25', audioUrl: '/audio/artists/soft-and-furious/is-this-fruit-edible.mp3' },
      { title: 'Horizon Ending', duration: '2:54', audioUrl: '/audio/artists/soft-and-furious/horizon-ending.mp3' },
      { title: 'Powerful Stasis', duration: '3:58', audioUrl: '/audio/artists/soft-and-furious/powerful-stasis.mp3' },
      { title: 'And Never Come Back', duration: '4:03', audioUrl: '/audio/artists/soft-and-furious/and-never-come-back.mp3' },
    ],
  },
  // ── POP / CHIPTUNE ───────────────────────────────────
  {
    id: 'rolemusic',
    name: 'Rolemusic',
    genre: 'Pop',
    subgenre: 'Chiptune Pop / Retro Videogame',
    location: 'Southern Spain',
    license: 'CC BY',
    fmaUrl: 'https://freemusicarchive.org/music/Rolemusic/',
    albumTitle: 'The Black Dot',
    imageUrl: 'https://freemusicarchive.org/image/?file=images%2Fartists%2FRolemusic_-_2014110872413390.png&width=290&height=290&type=artist',
    bio: 'Rolemusic is a chiptune musician from the south of Spain who makes catchy, melodic pop music using old machines like the ZX Spectrum and Game Boy. With over 1.4 million plays on Free Music Archive, their retro videogame sound proves that some of the best music comes from the simplest tools.',
    whyInteresting: 'Makes beautiful pop melodies using nothing but vintage gaming hardware — a ZX Spectrum and a Game Boy — proving you don\'t need expensive gear to make great music.',
    tags: ['chiptune', '8-bit', 'retro', 'videogame', 'pop', 'spain'],
    formed: '2010',
    members: 'Solo',
    totalAlbums: 8,
    instruments: ['ZX Spectrum', 'Game Boy', 'Chiptune Software'],
    moods: ['Playful', 'Catchy', 'Retro'],
    influences: ['Anamanaguchi', 'Chipzel', 'Classic Video Game Soundtracks'],
    similarArtists: ['komiku', 'soft-and-furious'],
    funFacts: [
      'Makes all music using old gaming hardware — a ZX Spectrum and a Game Boy',
      'Over 1.4 million plays on Free Music Archive — one of the most popular CC artists ever',
      'Track "Pokimonkey" is a fan favorite with a name that speaks for itself',
    ],
    tracks: [
      { title: 'The White Kitty', duration: '3:19', audioUrl: '/audio/artists/rolemusic/the-white-kitty.mp3' },
      { title: 'The White', duration: '2:20', audioUrl: '/audio/artists/rolemusic/the-white.mp3' },
      { title: 'Juglar Street', duration: '3:58', audioUrl: '/audio/artists/rolemusic/juglar-street.mp3' },
      { title: 'The Little Broth', duration: '4:15', audioUrl: '/audio/artists/rolemusic/the-little-broth.mp3' },
    ],
  },
  // ── ELECTRONIC / SYNTHWAVE ───────────────────────────
  {
    id: 'nihilore',
    name: 'Nihilore',
    genre: 'Electronic',
    subgenre: 'Synthwave / Downtempo / IDM',
    location: 'Australia',
    license: 'CC BY',
    fmaUrl: 'https://freemusicarchive.org/music/Nihilore/',
    albumTitle: 'Broken Parts',
    imageUrl: 'https://freemusicarchive.org/image/?file=artist_image%2FTSyElVTcgMPheHj12yKBaHGuqn5MxcYP2SOLoIaJ.png&width=290&height=290&type=artist',
    bio: 'Nihilore is an Australian electronic musician with a Bachelor of Music who takes a post-rock approach to electronic music — building big, cinematic crescendos instead of standard verse-chorus structures. With over 435,000 plays, their synthwave and downtempo tracks create entire worlds of sound.',
    whyInteresting: 'A classically trained musician who composes entirely in MIDI, proving that deep music theory knowledge combined with electronic tools can create truly powerful soundscapes.',
    tags: ['electronic', 'synthwave', 'downtempo', 'cinematic', 'australia', 'post-rock'],
    formed: '2012',
    members: 'Solo',
    totalAlbums: 10,
    instruments: ['MIDI Controllers', 'Cubase DAW', 'Synthesizers'],
    moods: ['Cinematic', 'Atmospheric', 'Intense'],
    influences: ['Boards of Canada', 'Tycho', 'Explosions in the Sky'],
    similarArtists: ['broke-for-free', 'soft-and-furious'],
    funFacts: [
      'Has a Bachelor of Music from the Australian Institute of Music',
      'Composes almost entirely in MIDI using Cubase — no live instruments',
      'Takes a post-rock approach to electronic music, building big crescendos instead of drops',
    ],
    tracks: [
      { title: 'Climbers In The Dark', duration: '6:37', audioUrl: '/audio/artists/nihilore/climbers-in-the-dark.mp3' },
      { title: 'Something Beautiful Is Going To Happen', duration: '5:30', audioUrl: '/audio/artists/nihilore/something-beautiful.mp3' },
      { title: 'So Does Hope', duration: '7:00', audioUrl: '/audio/artists/nihilore/so-does-hope.mp3' },
      { title: 'Brocken Spectre', duration: '5:00', audioUrl: '/audio/artists/nihilore/brocken-spectre.mp3' },
    ],
  },
  // ── ROCK / BLUES ROCK ────────────────────────────────
  {
    id: 'pierce-murphy',
    name: 'Pierce Murphy',
    genre: 'Rock',
    subgenre: 'Blues Rock / Indie Rock / Singer-Songwriter',
    location: 'Denver, Colorado',
    license: 'CC BY',
    fmaUrl: 'https://freemusicarchive.org/music/Pierce_Murphy/',
    albumTitle: 'Fellow Traveler',
    imageUrl: 'https://freemusicarchive.org/image/?file=image%2FH5omxl4a6g4SyZgsmZYs2dngzcva3Bb07ZbgXm7Q.jpeg&width=290&height=290&type=artist',
    bio: 'Pierce Murphy is a singer-songwriter and guitarist from Denver, Colorado who describes himself as "just a guy who grew up playing guitars and writing songs." His music spans blues rock, jazz, bossa nova, and indie rock — all played and recorded by him with a warm, authentic feel.',
    whyInteresting: 'A true DIY musician from Denver who plays every instrument and records everything himself — with nearly half a million plays proving that homemade music can reach the world.',
    tags: ['rock', 'blues', 'singer-songwriter', 'guitar', 'denver', 'indie'],
    formed: '2014',
    members: 'Solo',
    totalAlbums: 5,
    instruments: ['Guitar', 'Bass', 'Vocals', 'Keys'],
    moods: ['Warm', 'Groovy', 'Soulful'],
    influences: ['John Mayer', 'Jack Johnson', 'Bossa Nova'],
    similarArtists: ['josh-woodward', 'cullah'],
    funFacts: [
      'Describes himself as "just a guy who grew up playing guitars and writing songs in Denver"',
      'Nearly 475,000 plays on Free Music Archive',
      'His album "Through The Olive Branches" was inspired by travels through Mediterranean countries',
    ],
    tracks: [
      { title: 'Any Single Thing', duration: '3:00', audioUrl: '/audio/artists/pierce-murphy/any-single-thing.mp3' },
      { title: 'Baby, Write', duration: '3:30', audioUrl: '/audio/artists/pierce-murphy/baby-write.mp3' },
      { title: 'Persimmon', duration: '2:15', audioUrl: '/audio/artists/pierce-murphy/persimmon.mp3' },
      { title: 'Sparkling Impermanence', duration: '3:45', audioUrl: '/audio/artists/pierce-murphy/sparkling-impermanence.mp3' },
    ],
  },
  // ── ROCK / INDIE / LO-FI ─────────────────────────────
  {
    id: 'fog-lake',
    name: 'Fog Lake',
    genre: 'Rock',
    subgenre: 'Lo-fi Indie Rock / Shoegaze',
    location: 'Newfoundland, Canada',
    license: 'CC BY',
    fmaUrl: 'https://freemusicarchive.org/music/Fog_Lake/',
    albumTitle: 'Dragonchaser',
    imageUrl: 'https://freemusicarchive.org/image/?file=images%2Fartists%2FFog_Lake_-_2014121883003853.jpg&width=290&height=290&type=artist',
    bio: 'Fog Lake is a one-man band based on an island in Newfoundland, Canada who creates dreamy, atmospheric indie rock. With lo-fi production and soft, hazy vocals layered over shimmering guitars, the music feels like a foggy morning on the coast — beautiful, mysterious, and a little melancholy.',
    whyInteresting: 'A one-person band recording on a remote island, creating dreamy rock music that has reached over 220,000 plays — proving great music can come from the most isolated places.',
    tags: ['indie-rock', 'lo-fi', 'shoegaze', 'dreamy', 'island', 'canada'],
    formed: '2013',
    members: 'Solo',
    totalAlbums: 2,
    instruments: ['Guitar', 'Bass', 'Vocals', 'Drum Machine'],
    moods: ['Dreamy', 'Melancholy', 'Atmospheric'],
    influences: ['My Bloody Valentine', 'Beach House', 'Elliott Smith'],
    similarArtists: ['jahzzar', 'pierce-murphy'],
    funFacts: [
      'Records all music alone on an island in Newfoundland, Canada',
      'Over 220,000 plays on Free Music Archive',
      'Track "roswell" is named after the famous UFO site — the music sounds just as mysterious',
    ],
    tracks: [
      { title: 'spectrogram', duration: '3:00', audioUrl: '/audio/artists/fog-lake/spectrogram.mp3' },
      { title: 'push', duration: '4:00', audioUrl: '/audio/artists/fog-lake/push.mp3' },
      { title: 'oak island', duration: '2:40', audioUrl: '/audio/artists/fog-lake/oak-island.mp3' },
      { title: 'roswell', duration: '2:33', audioUrl: '/audio/artists/fog-lake/roswell.mp3' },
    ],
  },
  // ── COUNTRY / ACOUSTIC ───────────────────────────────
  {
    id: 'jason-shaw',
    name: 'Jason Shaw',
    genre: 'Folk / Country',
    subgenre: 'Country / Acoustic / Blues',
    location: 'Pittsburgh, Pennsylvania',
    license: 'CC BY',
    fmaUrl: 'https://freemusicarchive.org/music/Jason_Shaw/',
    albumTitle: 'Audionautix: Acoustic',
    imageUrl: 'https://freemusicarchive.org/image/?file=images%2Fartists%2FJason_Shaw_-_20131120155444083.jpg&width=290&height=290&type=artist',
    bio: 'Jason Shaw started studying music at 10 years old with the clarinet and eventually picked up guitar, piano, and bass. He runs Audionautix, a one-man operation creating production music across 28 different genres — with his Acoustic album racking up over 3 million plays and 3 million downloads.',
    whyInteresting: 'Started playing music at age 10 and built Audionautix into one of the most-used free music libraries in the world — over 3 million plays on just his Acoustic album alone.',
    tags: ['country', 'acoustic', 'blues', 'folk', 'pittsburgh', 'production-music'],
    formed: '2010',
    members: 'Solo',
    totalAlbums: 28,
    instruments: ['Guitar', 'Piano', 'Bass', 'Clarinet'],
    moods: ['Warm', 'Rustic', 'Relaxing'],
    influences: ['Country Tradition', 'Acoustic Blues', 'Folk'],
    similarArtists: ['josh-woodward', 'pierce-murphy'],
    funFacts: [
      'Started studying music at 10 years old with the clarinet',
      'His Acoustic album has over 3 million plays and 3 million downloads',
      'Creates music across 28 different genres — all by himself',
    ],
    tracks: [
      { title: "Jenny's Theme", duration: '1:30', audioUrl: '/audio/artists/jason-shaw/jennys-theme.mp3' },
      { title: 'Acoustic Blues', duration: '2:30', audioUrl: '/audio/artists/jason-shaw/acoustic-blues.mp3' },
      { title: '12 Mornings', duration: '2:20', audioUrl: '/audio/artists/jason-shaw/12-mornings.mp3' },
      { title: 'Words', duration: '2:25', audioUrl: '/audio/artists/jason-shaw/words.mp3' },
    ],
  },
  // ── FOLK / SINGER-SONGWRITER ─────────────────────────
  {
    id: 'david-mumford',
    name: 'David Mumford',
    genre: 'Folk / Country',
    subgenre: 'Folk / Singer-Songwriter / Americana',
    location: 'United States',
    license: 'CC BY',
    fmaUrl: 'https://freemusicarchive.org/music/David_Mumford/',
    albumTitle: 'Night Moves',
    imageUrl: 'https://freemusicarchive.org/image/?file=images%2Fartists%2FDavid_Mumford_-_20150709111738920.png&width=290&height=290&type=artist',
    bio: 'David Mumford creates warm, homemade folk songs with honest vocals and acoustic guitar. His music captures the feeling of small-town America — front porches, dusty roads, and real stories told with heart. Named an honorable mention on "Top 5 Creative Commons Musicians" lists.',
    whyInteresting: 'A true folk storyteller who proves that a guitar, a voice, and a good story are all you need to make music that connects with people.',
    tags: ['folk', 'singer-songwriter', 'americana', 'acoustic', 'vocals'],
    formed: '2015',
    members: 'Solo',
    totalAlbums: 1,
    instruments: ['Acoustic Guitar', 'Vocals'],
    moods: ['Warm', 'Honest', 'Rustic'],
    influences: ['Bob Dylan', 'Woody Guthrie', 'Townes Van Zandt'],
    similarArtists: ['josh-woodward', 'jason-shaw'],
    funFacts: [
      'Named an honorable mention on "Top 5 Creative Commons Musicians" lists',
      'Creates "homemade songs" with nothing but guitar and voice',
      'His music captures the feeling of small-town America and real storytelling',
    ],
    tracks: [
      { title: 'Darling Corina', duration: '3:00', audioUrl: '/audio/artists/david-mumford/darling-corina.mp3' },
      { title: 'The Worst Of It', duration: '2:45', audioUrl: '/audio/artists/david-mumford/the-worst-of-it.mp3' },
      { title: 'Ball And Chain', duration: '3:26', audioUrl: '/audio/artists/david-mumford/ball-and-chain.mp3' },
      { title: 'The Shelby Blues', duration: '3:00', audioUrl: '/audio/artists/david-mumford/the-shelby-blues.mp3' },
    ],
  },
  // ── FOLK / ACOUSTIC ──────────────────────────────────
  {
    id: 'austin-moffa',
    name: 'Austin Moffa',
    genre: 'Folk / Country',
    subgenre: 'Folk / Acoustic / Traditional',
    location: 'United States',
    license: 'CC BY',
    fmaUrl: 'https://freemusicarchive.org/music/austin-moffa/',
    albumTitle: "That's One Way to Spend Your Day",
    imageUrl: 'https://freemusicarchive.org/image/?file=image%2FrlxO8P7g5hJEnXUwcYi9LzbySeyvtWY7iaqlF2ma.jpeg&width=290&height=290&type=artist',
    bio: 'Austin Moffa is a folk musician who keeps the tradition of American folk music alive by performing both classic songs and original compositions. His acoustic guitar and warm voice carry on the storytelling tradition of artists like Woody Guthrie and Pete Seeger — songs about real people, real places, and real feelings.',
    whyInteresting: 'Keeps the American folk tradition alive by performing classic songs alongside his own originals — connecting today\'s listeners to a musical tradition that stretches back hundreds of years.',
    tags: ['folk', 'acoustic', 'traditional', 'americana', 'singer-songwriter'],
    formed: '2022',
    members: 'Solo',
    totalAlbums: 3,
    instruments: ['Acoustic Guitar', 'Vocals'],
    moods: ['Authentic', 'Warm', 'Timeless'],
    influences: ['Woody Guthrie', 'Pete Seeger', 'Doc Watson'],
    similarArtists: ['david-mumford', 'josh-woodward'],
    funFacts: [
      'Performs traditional folk songs like "Oh Shenandoah" and "Silver Dagger" alongside originals',
      'Over 55,000 plays on Free Music Archive across 44 tracks',
      'His music connects modern listeners to folk traditions stretching back hundreds of years',
    ],
    tracks: [
      { title: 'Roll On', duration: '3:20', audioUrl: '/audio/artists/austin-moffa/roll-on.mp3' },
      { title: 'The Interview', duration: '4:00', audioUrl: '/audio/artists/austin-moffa/the-interview.mp3' },
      { title: 'Some Kind of Morning', duration: '3:30', audioUrl: '/audio/artists/austin-moffa/some-kind-of-morning.mp3' },
      { title: 'Silver Dagger', duration: '3:15', audioUrl: '/audio/artists/austin-moffa/silver-dagger.mp3' },
    ],
  },
];

const ARTIST_DATABASE = ARTISTS;

// Genre list with colors matching the app theme
const GENRE_CONFIG = {
  'Hip-Hop':            { color: '#8b5cf6', icon: '🎤', bg: 'linear-gradient(135deg, #8b5cf6 0%, #3b82f6 100%)' },
  'Pop':                { color: '#ec4899', icon: '🎵', bg: 'linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%)' },
  'Rock':               { color: '#ef4444', icon: '⚡', bg: 'linear-gradient(135deg, #ef4444 0%, #f97316 100%)' },
  'R&B / Soul':         { color: '#f59e0b', icon: '🎙️', bg: 'linear-gradient(135deg, #f59e0b 0%, #ec4899 100%)' },
  'Electronic':         { color: '#06b6d4', icon: '🎹', bg: 'linear-gradient(135deg, #06b6d4 0%, #8b5cf6 100%)' },
  'Jazz':               { color: '#3b82f6', icon: '🎷', bg: 'linear-gradient(135deg, #3b82f6 0%, #6366f1 100%)' },
  'Latin':              { color: '#10b981', icon: '🔥', bg: 'linear-gradient(135deg, #10b981 0%, #14b8a6 100%)' },
  'Folk / Country':     { color: '#f97316', icon: '🎸', bg: 'linear-gradient(135deg, #f97316 0%, #f59e0b 100%)' },
  'World':              { color: '#14b8a6', icon: '🌍', bg: 'linear-gradient(135deg, #14b8a6 0%, #3b82f6 100%)' },
  'Indie / Alternative':{ color: '#a855f7', icon: '🎶', bg: 'linear-gradient(135deg, #a855f7 0%, #ec4899 100%)' },
};

const ALL_GENRES = Object.keys(GENRE_CONFIG);

function getArtistsByGenre(genre) {
  if (!genre || genre === 'All') return ARTIST_DATABASE;
  return ARTIST_DATABASE.filter(a => a.genre === genre);
}

function getArtistById(id) {
  return ARTIST_DATABASE.find(a => a.id === id) || null;
}

function getSimilarArtists(artistId) {
  const artist = getArtistById(artistId);
  if (!artist?.similarArtists) return [];
  return artist.similarArtists.map(id => getArtistById(id)).filter(Boolean);
}

export {
  ARTIST_DATABASE,
  GENRE_CONFIG,
  ALL_GENRES,
  getArtistsByGenre,
  getArtistById,
  getSimilarArtists,
};
