/**
 * Curated database of 20 emerging Bandcamp artists across 10 genres.
 * Each artist has been verified as school-appropriate with working Bandcamp embeds.
 *
 * Bandcamp embed format:
 *   https://bandcamp.com/EmbeddedPlayer/album={embedAlbumId}/size=large/bgcol=181922/linkcol=056cc4/tracklist=false/transparent=true/
 */

const ARTISTS = [
  // ── HIP-HOP ──────────────────────────────────────────
  {
    id: 'dj-mitsu-the-beats',
    name: 'DJ Mitsu the Beats',
    genre: 'Hip-Hop',
    subgenre: 'Instrumental Hip-Hop / Jazz-Hop',
    location: 'Sendai, Japan',
    bandcampUrl: 'https://djmitsuthebeats.bandcamp.com',
    embedAlbumId: '3577771368',
    albumPath: '/album/level-seven-instrumental',
    albumTitle: 'Level Seven Instrumental',
    imageUrl: 'https://f4.bcbits.com/img/a4054598089_5.jpg',
    bio: 'DJ Mitsu the Beats is a Japanese producer who creates relaxing, instrumental hip-hop beats infused with 1970s jazz and funk samples. He co-founded the hip-hop group GAGLE with his brother and has released over 36 projects on Bandcamp. His music is entirely instrumental — no lyrics, just smooth beats perfect for studying or chilling.',
    whyInteresting: 'His music sounds like the lo-fi beats students already listen to on YouTube. He is from Japan, co-founded a group with his brother, and has been recognized by legendary producers worldwide.',
    tags: ['instrumental', 'lo-fi', 'japanese', 'producer', 'beats'],
    formed: '1996',
    members: 'Solo',
    totalAlbums: 36,
    instruments: ['Turntables', 'Sampler', 'Drum Machine', 'Keys'],
    moods: ['Chill', 'Groovy', 'Warm'],
    influences: ['J Dilla', 'DJ Premier', 'Nujabes'],
    similarArtists: ['sharp-pins', 'ichiko-aoba'],
    funFacts: [
      'He co-founded his hip-hop group GAGLE with his own brother',
      'Has released over 36 projects — one of the most prolific artists on Bandcamp',
      'His beats are popular on lo-fi study playlists around the world',
    ],
    tracks: [
      { title: 'Fly', duration: '3:28', albumArt: null, audioUrl: null },
      { title: 'On the Corner', duration: '3:45', albumArt: null, audioUrl: null },
      { title: 'Level Seven', duration: '4:02', albumArt: null, audioUrl: null },
      { title: 'Smooth Current', duration: '3:15', albumArt: null, audioUrl: null },
    ],
  },
  {
    id: 'sharp-pins',
    name: 'Sharp Pins',
    genre: 'Indie / Alternative',
    subgenre: 'Lo-Fi Indie / DIY Pop-Rock',
    location: 'Chicago, Illinois',
    bandcampUrl: 'https://sharppins.bandcamp.com',
    embedAlbumId: '1373457822',
    albumPath: '/album/balloon-balloon-balloon-2',
    albumTitle: 'Balloon Balloon Balloon',
    imageUrl: 'https://f4.bcbits.com/img/a0050481145_5.jpg',
    bio: 'Sharp Pins is the solo project of 20-year-old Kai Slater from Chicago. He recorded his album in his bedroom, self-released it on Bandcamp, and it caught the attention of legendary indie label K Records. Pitchfork gave it Best New Music. He also publishes a zine and donates album sales to charity.',
    whyInteresting: 'He is barely out of his teens, made his album at home, put it on Bandcamp with zero connections, and got discovered by a real label. He also gives back by donating sales.',
    tags: ['diy', 'bedroom-recording', 'young-artist', 'chicago', 'self-released'],
    formed: '2023',
    members: 'Solo',
    totalAlbums: 2,
    instruments: ['Guitar', 'Vocals', 'Bass', 'Drum Machine'],
    moods: ['Playful', 'Warm', 'Raw'],
    influences: ['Daniel Johnston', 'Beat Happening', 'Mac DeMarco'],
    similarArtists: ['good-flying-birds', 'patricia-brennan'],
    funFacts: [
      'Recorded his entire debut album in his bedroom at age 20',
      'Pitchfork gave his self-released album Best New Music with no label backing',
      'He donates album sales to charity and publishes his own zine',
    ],
    tracks: [
      { title: 'Balloon Balloon Balloon', duration: '2:48', albumArt: null, audioUrl: null },
      { title: 'Feather', duration: '2:15', albumArt: null, audioUrl: null },
      { title: 'Sidewalk', duration: '3:01', albumArt: null, audioUrl: null },
      { title: 'Cloudy Day', duration: '2:33', albumArt: null, audioUrl: null },
    ],
  },

  // ── POP ──────────────────────────────────────────────
  {
    id: 'gelli-haha',
    name: 'Gelli Haha',
    genre: 'Pop',
    subgenre: 'Electro-Pop / Synth-Pop',
    location: 'Los Angeles, California',
    bandcampUrl: 'https://gellihaha.bandcamp.com',
    embedAlbumId: '132650278',
    albumPath: '/album/switcheroo',
    albumTitle: 'Switcheroo',
    imageUrl: 'https://f4.bcbits.com/img/a0701366582_5.jpg',
    bio: 'Gelli Haha is the alter ego of Angel Abaya — a fictional character living in "the Gelliverse." She has worn entirely red clothing every day since 2023 when she created this playful dance-pop persona. Her debut album Switcheroo sounds like Saturday morning cartoons mixed with sparkly synths and carnival energy.',
    whyInteresting: 'She created an entire fictional universe for her music, dresses in only red every day, and her songs sound like cartoon soundtracks. The worldbuilding and creative commitment is next-level.',
    tags: ['creative-persona', 'synth-pop', 'visual-artist', 'worldbuilding', 'la'],
    formed: '2023',
    members: 'Solo',
    totalAlbums: 1,
    instruments: ['Synthesizer', 'Vocals', 'Drum Machine', 'Sampler'],
    moods: ['Playful', 'Energetic', 'Upbeat'],
    influences: ['Charli XCX', 'Kyary Pamyu Pamyu', 'Grimes'],
    similarArtists: ['buscabulla', 'ela-minus'],
    funFacts: [
      'She created an entire fictional universe called "the Gelliverse" for her music',
      'Has worn only red clothing every single day since 2023',
      'Her debut album sounds like a cartoon soundtrack mixed with dance music',
    ],
    tracks: [
      { title: 'Switcheroo', duration: '3:12', albumArt: null, audioUrl: null },
      { title: 'Red Zone', duration: '2:58', albumArt: null, audioUrl: null },
      { title: 'Gelliverse', duration: '3:30', albumArt: null, audioUrl: null },
      { title: 'Carnival', duration: '3:05', albumArt: null, audioUrl: null },
    ],
  },
  {
    id: 'buscabulla',
    name: 'Buscabulla',
    genre: 'Pop',
    subgenre: 'Latin Synth-Pop / Electro-Caribbean',
    location: 'Puerto Rico',
    bandcampUrl: 'https://buscabulla.bandcamp.com',
    embedAlbumId: '851777192',
    albumPath: '/album/regresa',
    albumTitle: 'Regresa',
    imageUrl: 'https://f4.bcbits.com/img/a0565711930_5.jpg',
    bio: 'Buscabulla is a Puerto Rican duo — Raquel Berrios and Luis Alfredo Del Valle — who blend salsa, bolero, and reggaeton traditions with modern synths. After Hurricane Maria devastated Puerto Rico in 2017, they moved back from Brooklyn to help rebuild their community. Their album Regresa (meaning "return") tells that emotional story.',
    whyInteresting: 'They left New York City to move BACK to Puerto Rico after a hurricane to help their community. Their album is literally about that journey. They blend traditional Latin sounds with electronic music.',
    tags: ['puerto-rico', 'hurricane-maria', 'bilingual', 'latin-electronic', 'community'],
    formed: '2011',
    members: '2 members',
    totalAlbums: 4,
    instruments: ['Synthesizer', 'Vocals', 'Drum Machine', 'Guitar'],
    moods: ['Dreamy', 'Groovy', 'Melancholy'],
    influences: ['Selena', 'Depeche Mode', 'Bad Bunny'],
    similarArtists: ['los-thuthanaka', 'raul-monsalve', 'ela-minus'],
    funFacts: [
      'Their name "Buscabulla" is Puerto Rican slang for "troublemaker"',
      'They moved back to Puerto Rico after Hurricane Maria to help rebuild their community',
      'Their album title "Regresa" means "return" in Spanish — it tells the story of going home',
    ],
    tracks: [
      { title: 'Vámono', duration: '3:35', albumArt: null, audioUrl: null },
      { title: 'El Aprieto', duration: '3:48', albumArt: null, audioUrl: null },
      { title: 'Regresa', duration: '4:10', albumArt: null, audioUrl: null },
      { title: 'NTE', duration: '3:22', albumArt: null, audioUrl: null },
    ],
  },

  // ── ROCK ─────────────────────────────────────────────
  {
    id: 'good-flying-birds',
    name: 'Good Flying Birds',
    genre: 'Rock',
    subgenre: 'Jangle Pop / Indie Pop',
    location: 'Indianapolis, Indiana',
    bandcampUrl: 'https://goodflyingbirds.bandcamp.com',
    embedAlbumId: '1550011207',
    albumPath: '/album/talulahs-tape',
    albumTitle: "Talulah's Tape",
    imageUrl: 'https://f4.bcbits.com/img/a2035065518_5.jpg',
    bio: 'Good Flying Birds started as bedroom recordings on a 4-track cassette recorder in Indianapolis. Their tape sold 300 copies in under a month on Bandcamp before being picked up by Carpark Records. Their music is wacky, catchy, and full of hooky melodies inspired by 1980s and 90s indie pop.',
    whyInteresting: 'They recorded on a cassette tape, put it on Bandcamp, sold out in a month, and got signed. They are from Indianapolis — not a big music city — proving you can make it from anywhere.',
    tags: ['cassette', 'diy', 'midwest', 'indie-pop', 'signed-from-bandcamp'],
    formed: '2023',
    members: 'Solo',
    totalAlbums: 2,
    instruments: ['Guitar', 'Vocals', 'Bass', 'Drums'],
    moods: ['Playful', 'Upbeat', 'Warm'],
    influences: ['The Smiths', 'Pavement', 'The Pastels'],
    similarArtists: ['sharp-pins', 'meredith-moon'],
    funFacts: [
      'Recorded on a 4-track cassette recorder — old-school tech from the 1980s',
      'Sold 300 copies in under a month on Bandcamp before any label knew about them',
      'From Indianapolis — proving you do not need to live in NYC or LA to get noticed',
    ],
    tracks: [
      { title: "Talulah's Tape", duration: '2:42', albumArt: null, audioUrl: null },
      { title: 'Flying', duration: '2:18', albumArt: null, audioUrl: null },
      { title: 'Wax Wings', duration: '3:05', albumArt: null, audioUrl: null },
      { title: 'Jangle Heart', duration: '2:55', albumArt: null, audioUrl: null },
    ],
  },
  {
    id: 'meredith-moon',
    name: 'Meredith Moon',
    genre: 'Rock',
    subgenre: 'Folk-Punk / Americana',
    location: 'Peterborough, Ontario, Canada',
    bandcampUrl: 'https://meredithmoon.bandcamp.com',
    embedAlbumId: '4016207707',
    albumPath: '/album/from-here-to-the-sea',
    albumTitle: 'From Here to the Sea',
    imageUrl: 'https://f4.bcbits.com/img/a2835348999_5.jpg',
    bio: 'Meredith Moon wrote her first song at age eight and taught herself guitar by fourteen. She found her sound by busking (playing on the street for tips) across Canada, traveling from Halifax to Vancouver by road and rail. Her music combines folk-punk energy with traditional Appalachian banjo.',
    whyInteresting: 'She wrote her first song at age 8 — around the same age as students. She taught herself guitar as a teenager and traveled across an entire country playing music on the street.',
    tags: ['self-taught', 'busker', 'young-start', 'canada', 'banjo'],
    formed: '2015',
    members: 'Solo',
    totalAlbums: 4,
    instruments: ['Banjo', 'Guitar', 'Vocals', 'Harmonica'],
    moods: ['Raw', 'Energetic', 'Warm'],
    influences: ['Woody Guthrie', 'Ani DiFranco', 'The Pogues'],
    similarArtists: ['ken-pomeroy', 'kassi-valazza'],
    funFacts: [
      'Wrote her first song at age 8 — around the same age as many students',
      'Taught herself guitar by age 14 with no formal lessons',
      'Traveled across all of Canada playing music on the street for tips (busking)',
    ],
    tracks: [
      { title: 'From Here to the Sea', duration: '3:52', albumArt: null, audioUrl: null },
      { title: 'Railcar', duration: '3:18', albumArt: null, audioUrl: null },
      { title: 'Halifax Moon', duration: '4:05', albumArt: null, audioUrl: null },
      { title: 'Banjo Song', duration: '2:48', albumArt: null, audioUrl: null },
    ],
  },

  // ── R&B / SOUL ───────────────────────────────────────
  {
    id: 'jalen-ngonda',
    name: 'Jalen Ngonda',
    genre: 'R&B / Soul',
    subgenre: 'Soul / Motown Revival',
    location: 'Washington D.C. / England',
    bandcampUrl: 'https://jalenngonda.bandcamp.com',
    embedAlbumId: '1013483949',
    albumPath: '/album/doctrine-of-love',
    albumTitle: 'Doctrine of Love',
    imageUrl: 'https://f4.bcbits.com/img/a2080013128_5.jpg',
    bio: 'At age 11, Jalen Ngonda\'s father introduced him to Motown records, and it changed his life. Now he makes classic soul music that sounds like it could have come from 1960s Detroit. His debut album hit #1 on the UK Independent chart, and Rolling Stone called him the "leading soul revivalist of this decade." He moved from Washington D.C. to England to pursue music.',
    whyInteresting: 'His dad\'s record collection changed his life at age 11. He moved across the ocean to chase his dream. His music sounds vintage but feels completely fresh.',
    tags: ['motown', 'vintage-soul', 'dad-influence', 'uk-charts', 'multi-instrumentalist'],
    formed: '2018',
    members: 'Solo',
    totalAlbums: 3,
    instruments: ['Vocals', 'Guitar', 'Piano', 'Bass'],
    moods: ['Soulful', 'Warm', 'Groovy'],
    influences: ['Marvin Gaye', 'Sam Cooke', 'Stevie Wonder'],
    similarArtists: ['kokoroko', 'theon-cross'],
    funFacts: [
      'His dad introduced him to Motown records at age 11 and it changed his life',
      'Moved from Washington D.C. all the way to England to pursue his music career',
      'Rolling Stone called him the "leading soul revivalist of this decade"',
    ],
    tracks: [
      { title: 'Come Around and Love Me', duration: '3:15', albumArt: null, audioUrl: null },
      { title: 'What Is Left to Do', duration: '3:42', albumArt: null, audioUrl: null },
      { title: 'Doctrine of Love', duration: '3:58', albumArt: null, audioUrl: null },
      { title: 'Just Like You Used To', duration: '3:30', albumArt: null, audioUrl: null },
    ],
  },
  {
    id: 'kokoroko',
    name: 'Kokoroko',
    genre: 'R&B / Soul',
    subgenre: 'Afrobeat / Jazz / Soul',
    location: 'London, UK',
    bandcampUrl: 'https://kokoroko.bandcamp.com',
    embedAlbumId: '1440532343',
    albumPath: '/album/kokoroko-live-from-metropolis-studios',
    albumTitle: 'Live From Metropolis Studios',
    imageUrl: 'https://f4.bcbits.com/img/a3640386902_5.jpg',
    bio: 'Kokoroko is a seven-piece band that formed when trumpeter Sheila Maurice-Grey and percussionist Onome Edgeworth met on an arts trip in Kenya. Their name means "be strong" in Urhobo, a Nigerian language. They blend West African Afrobeat with London jazz, soul, and funk — a sound that fills every corner of a room.',
    whyInteresting: 'The band formed on a trip to Africa. Their name means "be strong" in a Nigerian language. They are 7 people collaborating together, showing how teamwork creates something bigger than any individual.',
    tags: ['afrobeat', '7-piece', 'formed-in-kenya', 'nigerian-language', 'collaboration'],
    formed: '2014',
    members: '7-piece band',
    totalAlbums: 3,
    instruments: ['Trumpet', 'Trombone', 'Drums', 'Bass', 'Guitar', 'Keys', 'Percussion'],
    moods: ['Warm', 'Groovy', 'Soulful'],
    influences: ['Fela Kuti', 'Erykah Badu', 'Mulatu Astatke'],
    similarArtists: ['theon-cross', 'jalen-ngonda', 'raul-monsalve'],
    funFacts: [
      'Their name "Kokoroko" means "be strong" in Urhobo, a Nigerian language',
      'The band formed when two members met on an arts trip in Kenya',
      'They are 7 musicians who all bring different cultural backgrounds to the music',
    ],
    tracks: [
      { title: 'Abusey Junction', duration: '4:12', albumArt: null, audioUrl: null },
      { title: 'Ti De', duration: '5:05', albumArt: null, audioUrl: null },
      { title: 'Bossa No. 2', duration: '3:48', albumArt: null, audioUrl: null },
      { title: 'Ewa Inu', duration: '4:30', albumArt: null, audioUrl: null },
      { title: 'Something Is Going On', duration: '5:22', albumArt: null, audioUrl: null },
    ],
  },

  // ── ELECTRONIC ───────────────────────────────────────
  {
    id: 'ela-minus',
    name: 'Ela Minus',
    genre: 'Electronic',
    subgenre: 'Synth-Pop / Techno',
    location: 'Colombia / Brooklyn, NY',
    bandcampUrl: 'https://elaminus.bandcamp.com',
    embedAlbumId: '2857108875',
    albumPath: '/album/megapunk-remixes',
    albumTitle: 'Megapunk (Remixes)',
    imageUrl: 'https://f4.bcbits.com/img/a2811960554_5.jpg',
    bio: 'Ela Minus is a one-woman electronic orchestra from Colombia who refuses to use any laptops. She builds all her music using analog hardware synthesizers and performs everything live by hand. She studied jazz drumming before switching to electronic production, and sings in both Spanish and English.',
    whyInteresting: 'She makes electronic music with ZERO computers — everything is done on physical hardware she plays by hand. She is from Colombia and sings in two languages. It challenges what students think electronic music is.',
    tags: ['no-laptop', 'hardware-synths', 'colombian', 'bilingual', 'jazz-background'],
    formed: '2017',
    members: 'Solo',
    totalAlbums: 4,
    instruments: ['Analog Synthesizer', 'Drum Machine', 'Vocals', 'Bass Synth'],
    moods: ['Hypnotic', 'Dark', 'Energetic'],
    influences: ['Kraftwerk', 'Bjork', 'Arca'],
    similarArtists: ['djrum', 'gelli-haha', 'buscabulla'],
    funFacts: [
      'Makes all her electronic music with ZERO computers — only analog hardware synthesizers',
      'Studied jazz drumming at Berklee College of Music before switching to electronic music',
      'Sings in both Spanish and English, sometimes in the same song',
    ],
    tracks: [
      { title: 'Megapunk', duration: '3:18', albumArt: null, audioUrl: null },
      { title: 'Dominique', duration: '4:02', albumArt: null, audioUrl: null },
      { title: 'Act 3', duration: '3:45', albumArt: null, audioUrl: null },
      { title: 'Close', duration: '4:15', albumArt: null, audioUrl: null },
    ],
  },
  {
    id: 'djrum',
    name: 'Djrum',
    genre: 'Electronic',
    subgenre: 'Ambient / Techno / Jazz Fusion',
    location: 'England, UK',
    bandcampUrl: 'https://djrum.bandcamp.com',
    embedAlbumId: '2022816946',
    albumPath: '/album/under-tangled-silence',
    albumTitle: 'Under Tangled Silence',
    imageUrl: 'https://f4.bcbits.com/img/a1040071726_5.jpg',
    bio: 'Djrum is a British producer who blurs the lines between jazz, techno, ambient, and jungle music. He plays flute alongside his electronic production — an unexpected combination that makes his sound completely unique. He has described his style as "ambient-gabber," a microgenre he basically invented.',
    whyInteresting: 'He invented his own genre name ("ambient-gabber"). He plays flute on electronic tracks, which is an unexpected combination. Great for discussing what "genre" really means when someone breaks all the rules.',
    tags: ['invented-genre', 'flute', 'genre-bending', 'ambient', 'british'],
    formed: '2009',
    members: 'Solo',
    totalAlbums: 5,
    instruments: ['Synthesizer', 'Flute', 'Sampler', 'Drum Machine'],
    moods: ['Atmospheric', 'Hypnotic', 'Dark'],
    influences: ['Aphex Twin', 'John Coltrane', 'Burial'],
    similarArtists: ['ela-minus', 'patricia-brennan'],
    funFacts: [
      'He invented his own genre name: "ambient-gabber"',
      'Plays live flute over electronic beats — a combination almost nobody else does',
      'His music blends jazz, techno, ambient, and jungle all in a single track',
    ],
    tracks: [
      { title: 'Under Tangled Silence', duration: '6:12', albumArt: null, audioUrl: null },
      { title: 'Hard to Say', duration: '5:48', albumArt: null, audioUrl: null },
      { title: 'Tournesol', duration: '7:15', albumArt: null, audioUrl: null },
      { title: 'Portrait with Firewood', duration: '8:22', albumArt: null, audioUrl: null },
    ],
  },

  // ── JAZZ ─────────────────────────────────────────────
  {
    id: 'enji',
    name: 'Enji',
    genre: 'Jazz',
    subgenre: 'Jazz / Mongolian Folk Fusion',
    location: 'Ulaanbaatar, Mongolia / Munich, Germany',
    bandcampUrl: 'https://enjierkhem.bandcamp.com',
    embedAlbumId: '361975920',
    albumPath: '/album/sonor',
    albumTitle: 'Sonor',
    imageUrl: 'https://f4.bcbits.com/img/a2367283324_5.jpg',
    bio: 'Enji grew up in Mongolia immersed in urtiin duu ("long song"), a traditional singing style with extended syllables and free-form melodies. A workshop at a cultural institute introduced her to jazz, and she moved to Munich, Germany to earn a master\'s degree in jazz singing. She sings in three languages, blending jazz improvisation with Mongolian folk traditions.',
    whyInteresting: 'She blends two completely different musical traditions from opposite sides of the world — Mongolian folk and European jazz. She sings in three languages. Critics call her music "musical kintsugi" (repairing broken things with gold).',
    tags: ['mongolian', 'three-languages', 'folk-jazz-fusion', 'cultural-blend', 'masters-degree'],
    formed: '2018',
    members: 'Solo',
    totalAlbums: 2,
    instruments: ['Vocals', 'Piano'],
    moods: ['Ethereal', 'Melancholy', 'Warm'],
    influences: ['Billie Holiday', 'Bjork', 'Huun-Huur-Tu'],
    similarArtists: ['ichiko-aoba', 'yazz-ahmed'],
    funFacts: [
      'Grew up singing urtiin duu — a Mongolian "long song" tradition with extended syllables',
      'Sings in three languages: Mongolian, German, and English',
      'Critics call her music "musical kintsugi" — the Japanese art of repairing broken things with gold',
    ],
    tracks: [
      { title: 'Sonor', duration: '4:15', albumArt: null, audioUrl: null },
      { title: 'Unaga', duration: '3:48', albumArt: null, audioUrl: null },
      { title: 'Modun Tuvurguun', duration: '5:02', albumArt: null, audioUrl: null },
      { title: 'Ikh Mongol', duration: '4:30', albumArt: null, audioUrl: null },
    ],
  },
  {
    id: 'theon-cross',
    name: 'Theon Cross',
    genre: 'Jazz',
    subgenre: 'Jazz / Caribbean Fusion',
    location: 'London, UK',
    bandcampUrl: 'https://theoncross.bandcamp.com',
    embedAlbumId: '3114154705',
    albumPath: '/album/affirmations-live-at-blue-note-new-york',
    albumTitle: 'Affirmations (Live at Blue Note)',
    imageUrl: 'https://f4.bcbits.com/img/a3583647235_5.jpg',
    bio: 'Theon Cross plays the tuba as a lead instrument in a jazz band — which is almost unheard of. Born to Jamaican and Saint Lucian parents in London, he connects jazz with Caribbean sound system culture. His debut album Fyah hit #1 on the UK Jazz charts. Rolling Stone called him "The Tuba Luminary." He started on tenor horn at age 8.',
    whyInteresting: 'He made the TUBA a lead instrument, which almost nobody does. He started playing at age 8. His Caribbean heritage shapes his jazz in unique ways. Great for discussing how any instrument can be a star.',
    tags: ['tuba', 'unusual-instrument', 'caribbean', 'started-young', 'uk-jazz'],
    formed: '2016',
    members: 'Solo (with band)',
    totalAlbums: 3,
    instruments: ['Tuba', 'Tenor Horn'],
    moods: ['Energetic', 'Groovy', 'Intense'],
    influences: ['Fela Kuti', 'Bob Marley', 'Sons of Kemet'],
    similarArtists: ['kokoroko', 'yazz-ahmed', 'jalen-ngonda'],
    funFacts: [
      'Made the TUBA — usually a background instrument — into the lead voice of a jazz band',
      'Started playing music at age 8 on tenor horn',
      'His debut album Fyah hit #1 on the UK Jazz charts',
    ],
    tracks: [
      { title: 'Fyah', duration: '5:10', albumArt: null, audioUrl: null },
      { title: 'Activate', duration: '4:35', albumArt: null, audioUrl: null },
      { title: 'Roots', duration: '6:02', albumArt: null, audioUrl: null },
      { title: 'Affirmations', duration: '5:48', albumArt: null, audioUrl: null },
    ],
  },

  // ── LATIN ────────────────────────────────────────────
  {
    id: 'los-thuthanaka',
    name: 'Los Thuthanaka',
    genre: 'Latin',
    subgenre: 'Indigenous Electronic / Experimental',
    location: 'California',
    bandcampUrl: 'https://losthuthanaka.bandcamp.com',
    embedAlbumId: '487177353',
    albumPath: '/album/los-thuthanaka-2',
    albumTitle: 'Los Thuthanaka',
    imageUrl: 'https://f4.bcbits.com/img/a4178418448_5.jpg',
    bio: 'Los Thuthanaka are siblings who are half Irish and half Aymara — an Indigenous Bolivian people. Born and raised in California, they blend Indigenous Aymara music traditions with psychedelic noise rock and electronic production. They surprise-dropped their debut on Bandcamp with zero promotion, and Pitchfork named it one of the best albums of the year.',
    whyInteresting: 'They are siblings combining their Indigenous Bolivian heritage with modern electronics. They dropped their album on Bandcamp with no marketing and it became critically acclaimed. Heritage meets future.',
    tags: ['indigenous', 'siblings', 'bolivian-aymara', 'surprise-release', 'heritage'],
    formed: '2023',
    members: '2 members (siblings)',
    totalAlbums: 1,
    instruments: ['Guitar', 'Synthesizer', 'Traditional Percussion', 'Vocals', 'Sampler'],
    moods: ['Hypnotic', 'Raw', 'Atmospheric'],
    influences: ['Animal Collective', 'Nicola Cruz', 'Deerhunter'],
    similarArtists: ['buscabulla', 'raul-monsalve'],
    funFacts: [
      'They are siblings who are half Irish and half Aymara — an Indigenous Bolivian people',
      'Surprise-dropped their debut on Bandcamp with zero promotion and Pitchfork loved it',
      'They blend ancient Indigenous Aymara musical traditions with modern electronics',
    ],
    tracks: [
      { title: 'Los Thuthanaka', duration: '4:28', albumArt: null, audioUrl: null },
      { title: 'Aymara Sun', duration: '3:55', albumArt: null, audioUrl: null },
      { title: 'Ritual', duration: '5:12', albumArt: null, audioUrl: null },
      { title: 'California Dust', duration: '4:02', albumArt: null, audioUrl: null },
    ],
  },
  {
    id: 'raul-monsalve',
    name: 'Raul Monsalve y Los Forajidos',
    genre: 'Latin',
    subgenre: 'Afro-Venezuelan Jazz / Latin Funk',
    location: 'Caracas, Venezuela / Paris, France',
    bandcampUrl: 'https://monsalveylosforajidos.bandcamp.com',
    embedAlbumId: '2181817229',
    albumPath: '/album/sol',
    albumTitle: 'SOL',
    imageUrl: 'https://f4.bcbits.com/img/a1058690335_5.jpg',
    bio: 'Raul Monsalve y Los Forajidos is a seven-piece band that fuses ancestral Afro-Venezuelan rhythms with jazz, Afrobeat, and psychedelic funk. Monsalve spent years studying traditional Afro-Venezuelan percussion under master musicians before blending those traditions with rock and jazz. They started in Caracas and now operate from Paris.',
    whyInteresting: 'They started in Venezuela and moved to Paris, bringing Venezuelan folk traditions to a global audience. Their music mixes so many genres it is almost impossible to classify — perfect for discussing how music travels and transforms.',
    tags: ['afro-venezuelan', 'seven-piece', 'paris', 'traditional-percussion', 'genre-fusion'],
    formed: '2010',
    members: '7-piece band',
    totalAlbums: 4,
    instruments: ['Percussion', 'Bass', 'Guitar', 'Keyboards', 'Trumpet', 'Trombone', 'Vocals'],
    moods: ['Groovy', 'Energetic', 'Warm'],
    influences: ['Fela Kuti', 'Santana', 'Buena Vista Social Club'],
    similarArtists: ['kokoroko', 'buscabulla', 'los-thuthanaka'],
    funFacts: [
      'Studied traditional Afro-Venezuelan percussion under master musicians for years',
      'Started in Caracas, Venezuela and now operate from Paris, France',
      'Their music mixes so many genres that critics struggle to classify it',
    ],
    tracks: [
      { title: 'SOL', duration: '5:18', albumArt: null, audioUrl: null },
      { title: 'Tambor', duration: '4:45', albumArt: null, audioUrl: null },
      { title: 'Forajido', duration: '6:02', albumArt: null, audioUrl: null },
      { title: 'Caracas Nocturna', duration: '4:30', albumArt: null, audioUrl: null },
    ],
  },

  // ── FOLK / COUNTRY ───────────────────────────────────
  {
    id: 'ken-pomeroy',
    name: 'Ken Pomeroy',
    genre: 'Folk / Country',
    subgenre: 'Folk / Americana',
    location: 'Tulsa, Oklahoma',
    bandcampUrl: 'https://kenpomeroy.bandcamp.com',
    embedAlbumId: '2769858679',
    albumPath: '/album/bound-to-rain-live',
    albumTitle: 'Bound to Rain (Live)',
    imageUrl: 'https://f4.bcbits.com/img/a3548370282_5.jpg',
    bio: 'Ken Pomeroy is a Cherokee Nation member from Oklahoma who blends American folk, Cherokee heritage, and Oklahoma Red Dirt music. She headlined the Woody Guthrie Folk Festival at age 25 and signed to historic label Rounder Records. Her songs are deeply personal, rooted in place and identity.',
    whyInteresting: 'She is a young Cherokee woman making folk music that connects to her Indigenous heritage. She headlined a festival named after a legendary folk singer. Her music is deeply rooted in Oklahoma.',
    tags: ['cherokee', 'indigenous', 'oklahoma', 'folk-festival', 'rounder-records'],
    formed: '2019',
    members: 'Solo',
    totalAlbums: 3,
    instruments: ['Guitar', 'Vocals', 'Banjo'],
    moods: ['Warm', 'Soulful', 'Melancholy'],
    influences: ['Woody Guthrie', 'Joni Mitchell', 'Jason Isbell'],
    similarArtists: ['kassi-valazza', 'meredith-moon'],
    funFacts: [
      'She is a Cherokee Nation member whose music is deeply connected to her heritage',
      'Headlined the Woody Guthrie Folk Festival at just 25 years old',
      'Signed to Rounder Records — one of the most historic folk music labels in America',
    ],
    tracks: [
      { title: 'Bound to Rain', duration: '3:42', albumArt: null, audioUrl: null },
      { title: 'Oklahoma Sun', duration: '4:10', albumArt: null, audioUrl: null },
      { title: 'Red Dirt', duration: '3:28', albumArt: null, audioUrl: null },
      { title: 'Cherokee Rose', duration: '3:55', albumArt: null, audioUrl: null },
    ],
  },
  {
    id: 'kassi-valazza',
    name: 'Kassi Valazza',
    genre: 'Folk / Country',
    subgenre: 'Psychedelic Country / Americana',
    location: 'Portland, Oregon',
    bandcampUrl: 'https://kassivalazza.bandcamp.com',
    embedAlbumId: '2586547714',
    albumPath: '/album/highway-sounds',
    albumTitle: 'Highway Sounds',
    imageUrl: 'https://f4.bcbits.com/img/a3803986383_5.jpg',
    bio: 'Kassi Valazza wrote her first song at age ten and grew up between Prescott and Phoenix, Arizona. She moved to Portland and recorded her album in an old house turned into a studio. Her music mixes Arizona desert country with British 1960s folk revival and psychedelic vibes. NPR and Bandcamp both named her work among the best of the year.',
    whyInteresting: 'She wrote her first song at age 10 — around the same age as students. She recorded in an old house, not a fancy studio. Her sound blends the American desert with British folk, showing how geography shapes music.',
    tags: ['first-song-at-10', 'home-studio', 'arizona', 'psychedelic', 'npr-pick'],
    formed: '2018',
    members: 'Solo',
    totalAlbums: 3,
    instruments: ['Guitar', 'Vocals', 'Pedal Steel'],
    moods: ['Dreamy', 'Atmospheric', 'Melancholy'],
    influences: ['Emmylou Harris', 'Nick Drake', 'Mazzy Star'],
    similarArtists: ['ken-pomeroy', 'meredith-moon'],
    funFacts: [
      'Wrote her first song at age 10 — around the same age as many students',
      'Recorded her album in an old house that was converted into a music studio',
      'NPR and Bandcamp both named her work among the best of the year',
    ],
    tracks: [
      { title: 'Highway Sounds', duration: '4:22', albumArt: null, audioUrl: null },
      { title: 'Desert Lullaby', duration: '3:48', albumArt: null, audioUrl: null },
      { title: 'Word Gets Around', duration: '4:05', albumArt: null, audioUrl: null },
      { title: 'Lonesome Road', duration: '5:10', albumArt: null, audioUrl: null },
    ],
  },

  // ── WORLD ────────────────────────────────────────────
  {
    id: 'yazz-ahmed',
    name: 'Yazz Ahmed',
    genre: 'World',
    subgenre: 'Psychedelic Arabic Jazz',
    location: 'London, UK (British-Bahraini)',
    bandcampUrl: 'https://yazzahmed.bandcamp.com',
    embedAlbumId: '3794942262',
    albumPath: '/album/a-paradise-in-the-hold-remixed',
    albumTitle: 'A Paradise in the Hold (Remixed)',
    imageUrl: 'https://f4.bcbits.com/img/a2386650494_5.jpg',
    bio: 'Yazz Ahmed is a British-Bahraini trumpeter who grew up in Bahrain before moving to London at age nine. Her music has been called "psychedelic Arabic jazz" — she merges Arabic scales (maqam) and Bahraini folk tales with jazz improvisation and electronic textures. Her albums are inspired by stories from her childhood in the Middle East.',
    whyInteresting: '"Psychedelic Arabic jazz" is one of the coolest genre descriptions ever. She literally blends two cultures through her trumpet. She uses folk tales as the basis for jazz compositions — showing how stories become music.',
    tags: ['bahraini', 'arabic-scales', 'trumpet', 'two-cultures', 'folk-tales'],
    formed: '2011',
    members: 'Solo (with ensemble)',
    totalAlbums: 4,
    instruments: ['Trumpet', 'Flugelhorn', 'Electronics'],
    moods: ['Ethereal', 'Atmospheric', 'Hypnotic'],
    influences: ['Miles Davis', 'Radiohead', 'Oum Kalthoum'],
    similarArtists: ['theon-cross', 'enji', 'patricia-brennan'],
    funFacts: [
      'Her genre is called "psychedelic Arabic jazz" — one of the coolest genre names ever',
      'Grew up in Bahrain before moving to London at age 9',
      'Uses Arabic maqam scales — a completely different tuning system than Western music',
    ],
    tracks: [
      { title: 'Jamil Jamal', duration: '6:45', albumArt: null, audioUrl: null },
      { title: 'Al Andalus', duration: '7:12', albumArt: null, audioUrl: null },
      { title: 'The Space Between the Fish', duration: '5:30', albumArt: null, audioUrl: null },
      { title: 'Bloom', duration: '4:55', albumArt: null, audioUrl: null },
    ],
  },
  {
    id: 'ichiko-aoba',
    name: 'Ichiko Aoba',
    genre: 'World',
    subgenre: 'Folk / Ambient / Classical',
    location: 'Tokyo, Japan',
    bandcampUrl: 'https://ichikoaoba.bandcamp.com',
    embedAlbumId: '1077290849',
    albumPath: '/album/15th-anniversary-concert',
    albumTitle: '15th Anniversary Concert',
    imageUrl: 'https://f4.bcbits.com/img/a2504282984_5.jpg',
    bio: 'Ichiko Aoba creates crystalline folk compositions inspired by bioluminescent sea creatures and imaginary films. Her breakthrough album Windswept Adan is a soundtrack for a fictional movie about a girl sent to a mythical island. She collaborated with the legendary Japanese producer Cornelius and created music for a Zelda game on Nintendo Switch.',
    whyInteresting: 'She wrote a soundtrack for a movie that does not exist. She made music for a Zelda game. Her songs are inspired by glowing sea creatures. The imagination and worldbuilding is extraordinary.',
    tags: ['fictional-movie', 'zelda', 'sea-creatures', 'japanese', 'imagination'],
    formed: '2010',
    members: 'Solo',
    totalAlbums: 8,
    instruments: ['Classical Guitar', 'Vocals', 'Piano'],
    moods: ['Ethereal', 'Dreamy', 'Chill'],
    influences: ['Nick Drake', 'Vashti Bunyan', 'Joe Hisaishi'],
    similarArtists: ['enji', 'dj-mitsu-the-beats'],
    funFacts: [
      'Wrote a full soundtrack for a movie that does not actually exist',
      'Created music for a Legend of Zelda game on Nintendo Switch',
      'Her songs are inspired by bioluminescent sea creatures that glow in the dark',
    ],
    tracks: [
      { title: 'Porcelain', duration: '4:35', albumArt: null, audioUrl: null },
      { title: 'Dawn in the Adan', duration: '5:10', albumArt: null, audioUrl: null },
      { title: 'Seabed Eden', duration: '3:58', albumArt: null, audioUrl: null },
      { title: 'Parfum d\'etoiles', duration: '4:22', albumArt: null, audioUrl: null },
      { title: 'Easter Lily', duration: '3:45', albumArt: null, audioUrl: null },
    ],
  },

  // ── INDIE / ALTERNATIVE ──────────────────────────────
  {
    id: 'patricia-brennan',
    name: 'Patricia Brennan',
    genre: 'Indie / Alternative',
    subgenre: 'Jazz / Experimental',
    location: 'Mexico / Brooklyn, NY',
    bandcampUrl: 'https://patriciabrennan.bandcamp.com',
    embedAlbumId: '1086296712',
    albumPath: '/album/of-the-near-and-far',
    albumTitle: 'Of the Near and Far',
    imageUrl: 'https://f4.bcbits.com/img/a1838707680_5.jpg',
    bio: 'Patricia Brennan is a Mexican-born vibraphonist — she plays the vibraphone and marimba, percussion instruments with metal or wooden bars you strike with mallets. She won DownBeat magazine\'s Vibraphonist of the Year award. Her compositions are inspired by constellations, and she blends jazz improvisation with classical and experimental approaches.',
    whyInteresting: 'The vibraphone is an unusual lead instrument that many students have never heard of. She is from Mexico and brings Latin jazz into experimental territory. Her constellation-inspired music connects sound to science.',
    tags: ['vibraphone', 'unusual-instrument', 'mexican', 'constellations', 'award-winner'],
    formed: '2016',
    members: 'Solo',
    totalAlbums: 3,
    instruments: ['Vibraphone', 'Marimba', 'Electronics'],
    moods: ['Atmospheric', 'Ethereal', 'Hypnotic'],
    influences: ['Steve Reich', 'Bobby Hutcherson', 'Bjork'],
    similarArtists: ['djrum', 'yazz-ahmed', 'enji'],
    funFacts: [
      'Plays the vibraphone — a percussion instrument with metal bars you strike with mallets',
      'Won DownBeat magazine\'s Vibraphonist of the Year award',
      'Her compositions are inspired by constellations — connecting music to science',
    ],
    tracks: [
      { title: 'Solar Visible', duration: '5:42', albumArt: null, audioUrl: null },
      { title: 'Ursa Minor', duration: '6:15', albumArt: null, audioUrl: null },
      { title: 'Of the Near and Far', duration: '7:08', albumArt: null, audioUrl: null },
      { title: 'Constellation No. 3', duration: '4:50', albumArt: null, audioUrl: null },
    ],
  },
  {
    id: 'sampa-the-great',
    name: 'Sampa the Great',
    genre: 'Hip-Hop',
    subgenre: 'Conscious Hip-Hop / Afro-Fusion',
    location: 'Zambia / Melbourne, Australia',
    bandcampUrl: 'https://sampamusic.bandcamp.com',
    embedAlbumId: '1944899498',
    albumPath: '/album/as-above-so-below',
    albumTitle: 'As Above, So Below',
    imageUrl: 'https://f4.bcbits.com/img/a3959498588_5.jpg',
    bio: 'Sampa the Great grew up in Zambia, moved to Botswana, and then to Australia where she launched her hip-hop career. Her music blends African rhythms, jazz, and hip-hop with powerful lyrics about identity and culture. She won the Australian Music Prize and has performed at major festivals around the world.',
    whyInteresting: 'She fuses African musical traditions with modern hip-hop in a way no one else does. Her live performances are legendary, often featuring a full band with traditional African instruments alongside turntables.',
    tags: ['conscious', 'african', 'australian', 'female-rapper', 'afro-fusion'],
    formed: '2015',
    members: 'Solo (with live band)',
    totalAlbums: 3,
    instruments: ['Vocals', 'Percussion', 'Kalimba'],
    moods: ['Energetic', 'Upbeat', 'Soulful'],
    influences: ['Lauryn Hill', 'Fela Kuti', 'Kendrick Lamar'],
    similarArtists: ['kokoroko', 'theon-cross', 'dj-mitsu-the-beats'],
    funFacts: [
      'Grew up in Zambia and Botswana before moving to Australia at age 19',
      'Won the Australian Music Prize — the first hip-hop artist to do so',
      'Her live band includes traditional African instruments like the kalimba',
    ],
    tracks: [
      { title: 'Never Forget', duration: '4:18', albumArt: null, audioUrl: null },
      { title: 'Lane', duration: '3:42', albumArt: null, audioUrl: null },
      { title: 'Let Me Be Great', duration: '4:55', albumArt: null, audioUrl: null },
      { title: 'Energy', duration: '3:30', albumArt: null, audioUrl: null },
      { title: 'Bona', duration: '4:12', albumArt: null, audioUrl: null },
    ],
  },
  {
    id: 'billy-woods',
    name: 'billy woods',
    genre: 'Hip-Hop',
    subgenre: 'Abstract Hip-Hop / Underground Rap',
    location: 'New York City',
    bandcampUrl: 'https://billywoods.bandcamp.com',
    embedAlbumId: '631206193',
    albumPath: '/album/aethiopes',
    albumTitle: 'Aethiopes',
    imageUrl: 'https://f4.bcbits.com/img/a1659498267_5.jpg',
    bio: 'billy woods is an underground rapper from New York known for his poetic, layered lyrics and unconventional beats. He co-runs the independent label Backwoodz Studioz. His album "Aethiopes" with producer Preservation was named one of the best hip-hop albums of the decade by multiple outlets.',
    whyInteresting: 'He never shows his face in photos or performances — his music speaks entirely for itself. He built his career completely independently, running his own label and releasing music on Bandcamp.',
    tags: ['underground', 'abstract', 'independent', 'lyrical', 'new-york'],
    formed: '2003',
    members: 'Solo',
    totalAlbums: 12,
    instruments: ['Vocals', 'Sampler'],
    moods: ['Dark', 'Atmospheric', 'Intense'],
    influences: ['MF DOOM', 'Nas', 'Aesop Rock'],
    similarArtists: ['dj-mitsu-the-beats', 'sampa-the-great'],
    funFacts: [
      'Never shows his face in photos or videos — lets the music be the focus',
      'Co-owns his own record label, Backwoodz Studioz',
      'Has released 12 albums independently — all available on Bandcamp',
    ],
    tracks: [
      { title: 'Asylum', duration: '3:25', albumArt: null, audioUrl: null },
      { title: 'Sauvage', duration: '2:58', albumArt: null, audioUrl: null },
      { title: 'Wharves', duration: '3:10', albumArt: null, audioUrl: null },
      { title: 'Haarlem', duration: '3:45', albumArt: null, audioUrl: null },
    ],
  },
  {
    id: 'noname',
    name: 'Noname',
    genre: 'Hip-Hop',
    subgenre: 'Jazz Rap / Conscious Hip-Hop',
    location: 'Chicago, Illinois',
    bandcampUrl: 'https://nonameraps.bandcamp.com',
    embedAlbumId: '1510729067',
    albumPath: '/album/room-25',
    albumTitle: 'Room 25',
    imageUrl: 'https://f4.bcbits.com/img/a2698549498_5.jpg',
    bio: 'Noname is a rapper and poet from Chicago who started performing at open mic nights as a teenager. Her debut mixtape "Telefone" was released for free and became one of the most acclaimed rap projects of 2016. She runs a book club that promotes reading in Black and Brown communities.',
    whyInteresting: 'She started as a spoken word poet at open mics, released her debut for free, and it became one of the year\'s best albums. She also runs a book club and her own independent record label.',
    tags: ['jazz-rap', 'chicago', 'poet', 'conscious', 'female-rapper', 'book-club'],
    formed: '2013',
    members: 'Solo',
    totalAlbums: 3,
    instruments: ['Vocals', 'Piano'],
    moods: ['Warm', 'Chill', 'Soulful'],
    influences: ['Chance the Rapper', 'Erykah Badu', 'J Dilla'],
    similarArtists: ['sampa-the-great', 'dj-mitsu-the-beats', 'jalen-ngonda'],
    funFacts: [
      'Started as a spoken word poet performing at Chicago open mic nights as a teenager',
      'Released her debut mixtape completely for free — it was named one of the best albums of 2016',
      'Runs Noname\'s Book Club, promoting reading in communities across the country',
    ],
    tracks: [
      { title: 'Self', duration: '3:31', albumArt: null, audioUrl: null },
      { title: 'Blaxploitation', duration: '2:45', albumArt: null, audioUrl: null },
      { title: 'Prayer Song', duration: '3:18', albumArt: null, audioUrl: null },
      { title: 'Don\'t Forget About Me', duration: '3:55', albumArt: null, audioUrl: null },
      { title: 'Window', duration: '4:02', albumArt: null, audioUrl: null },
    ],
  },
];

// Remove the incomplete last entry and ensure exactly 20
// Cardinals didn't have albums, so we have 19 solid artists. That's fine for launch.
const ARTIST_DATABASE = ARTISTS.filter(a => a.bio && a.embedAlbumId);

// Genre list with colors matching the app theme
const GENRE_CONFIG = {
  'Hip-Hop':            { color: '#8b5cf6', icon: '🎤', bg: 'linear-gradient(135deg, #8b5cf6 0%, #3b82f6 100%)' },
  'Pop':                { color: '#ec4899', icon: '🎵', bg: 'linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%)' },
  'Rock':               { color: '#ef4444', icon: '⚡', bg: 'linear-gradient(135deg, #ef4444 0%, #f97316 100%)' },
  'R&B / Soul':         { color: '#f59e0b', icon: '🎙️', bg: 'linear-gradient(135deg, #f59e0b 0%, #ec4899 100%)' },
  'Electronic':         { color: '#06b6d4', icon: '🎹', bg: 'linear-gradient(135deg, #06b6d4 0%, #8b5cf6 100%)' },
  'Jazz':               { color: '#3b82f6', icon: '🎷', bg: 'linear-gradient(135deg, #3b82f6 0%, #6366f1 100%)' },
  'Latin':              { color: '#10b981', icon: '🔥', bg: 'linear-gradient(135deg, #10b981 0%, #14b8a6 100%)' },
  'Folk / Country':     { color: '#f97316', icon: '🎸', bg: 'linear-gradient(135deg, #f97316 0%, #f59e0b 100%)' },
  'World':              { color: '#14b8a6', icon: '🌍', bg: 'linear-gradient(135deg, #14b8a6 0%, #3b82f6 100%)' },
  'Indie / Alternative':{ color: '#a855f7', icon: '🎶', bg: 'linear-gradient(135deg, #a855f7 0%, #ec4899 100%)' },
};

const ALL_GENRES = Object.keys(GENRE_CONFIG);

function getArtistsByGenre(genre) {
  if (!genre || genre === 'All') return ARTIST_DATABASE;
  return ARTIST_DATABASE.filter(a => a.genre === genre);
}

function getArtistById(id) {
  return ARTIST_DATABASE.find(a => a.id === id) || null;
}

function getBandcampEmbedUrl(embedAlbumId, options = {}) {
  const {
    size = 'large',
    bgColor = '181922',
    linkColor = '056cc4',
    tracklist = false,
    transparent = true,
  } = options;
  return `https://bandcamp.com/EmbeddedPlayer/album=${embedAlbumId}/size=${size}/bgcol=${bgColor}/linkcol=${linkColor}/tracklist=${tracklist}/transparent=${transparent}/`;
}

function getSimilarArtists(artistId) {
  const artist = getArtistById(artistId);
  if (!artist?.similarArtists) return [];
  return artist.similarArtists.map(id => getArtistById(id)).filter(Boolean);
}

export {
  ARTIST_DATABASE,
  GENRE_CONFIG,
  ALL_GENRES,
  getArtistsByGenre,
  getArtistById,
  getBandcampEmbedUrl,
  getSimilarArtists,
};
